-- phpMyAdmin SQL Dump
-- version 5.2.2deb1+noble1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: May 19, 2025 at 09:54 PM
-- Server version: 8.0.42-0ubuntu0.24.04.1
-- PHP Version: 8.3.17

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `test`
--

-- --------------------------------------------------------

--
-- Table structure for table `questions`
--

CREATE TABLE `questions` (
  `id` int NOT NULL,
  `area` varchar(100) COLLATE utf8mb4_slovak_ci NOT NULL,
  `area_en` varchar(100) COLLATE utf8mb4_slovak_ci NOT NULL,
  `text_sk` text COLLATE utf8mb4_slovak_ci NOT NULL,
  `text_en` text COLLATE utf8mb4_slovak_ci NOT NULL,
  `correct_answer` varchar(255) COLLATE utf8mb4_slovak_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_slovak_ci;

--
-- Dumping data for table `questions`
--

INSERT INTO `questions` (`id`, `area`, `area_en`, `text_sk`, `text_en`, `correct_answer`) VALUES
(1, 'Funkcie', 'Functions', 'MC: Je daná lineárna funkcia ( f(x) = 2x + 4 ). Nájdite jej nulové body.---\r\nA) Má jeden nulový bod: 4\r\nB) Žiadna z ostatných odpovedí nie je pravdivá.\r\nC) Má dva nulové body: 2 a 4\r\nD) Má jeden nulový bod: 2\r\nE) Nemá žiaden nulový bod.', 'MC: A linear function is given as ( f(x) = 2x + 4 ). Find its zero(s).---\r\nA) Has one zero: 4\r\nB) None of the other answers is correct.\r\nC) Has two zeros: 2 and 4\r\nD) Has one zero: 2\r\nE) Has no zero.', 'B'),
(4, 'Geometria', 'Geometry', 'MC: Uvažujme dva sústredné kruhy s polomermi ( r_1 ) a ( r_2 ). Vyberte veľkosti polomerov tak, aby veľkosť plochy medzikružia bola ( 3pi ).---\r\nA) ( r_1 = frac{3}{2}, r_2 = 3 )\r\nB) ( r_1 = 1, r_2 = 4 )\r\nC) ( r_1 = sqrt{5}, r_2 = 2sqrt{2} )\r\nD) ( r_1 = 3, r_2 = 12 )\r\nE) ( r_1 = sqrt{12}, r_2 = sqrt{6} )', 'MC: Consider two concentric circles with radii ( r_1 ) and ( r_2 ). Choose the radii so that the area of the ring is ( 3pi ).---\r\nA) ( r_1 = frac{3}{2}, r_2 = 3 )\r\nB) ( r_1 = 1, r_2 = 4 )\r\nC) ( r_1 = sqrt{5}, r_2 = 2sqrt{2} )\r\nD) ( r_1 = 3, r_2 = 12 )\r\nE) ( r_1 = sqrt{12}, r_2 = sqrt{6} )', 'C'),
(5, 'Rovnice', 'Equations', 'MC: Rovnica ( 2^x + frac{1}{2^x} = 2 )---\r\nA) má práve dve riešenia, ktorých súčin je 1.\r\nB) má práve dve riešenia, ktorých súčet je 2.\r\nC) má práve jedno riešenie.\r\nD) nemá žiadne riešenie.\r\nE) má práve dve riešenia, ktorých súčet je 0.', 'MC: Equation ( 2^x + frac{1}{2^x} = 2 )---\r\nA) has exactly two solutions whose product is 1.\r\nB) has exactly two solutions whose sum is 2.\r\nC) has exactly one solution.\r\nD) has no solution.\r\nE) has exactly two solutions whose sum is 0.', 'C'),
(6, 'Postupnosti', 'Sequences', 'MC: Nájdite súčet prvých piatich členov aritmetickej postupnosti ( a_1 + a_2 + a_3 + a_4 + a_5 ), ak viete, že ( a_2 + a_3 + a_4 = 9 )---\r\nA) ( a_1 + a_2 + a_3 + a_4 + a_5 = 18 )\r\nB) ( a_1 + a_2 + a_3 + a_4 + a_5 = 6 )\r\nC) Z uvedených údajov sa to nedá vypočítať.\r\nD) ( a_1 + a_2 + a_3 + a_4 + a_5 = 15 )\r\nE) ( a_1 + a_2 + a_3 + a_4 + a_5 = 9 )', 'MC: Find the sum of the first five terms of the arithmetic sequence ( a_1 + a_2 + a_3 + a_4 + a_5 ), given that ( a_2 + a_3 + a_4 = 9 )---\r\nA) ( a_1 + a_2 + a_3 + a_4 + a_5 = 18 )\r\nB) ( a_1 + a_2 + a_3 + a_4 + a_5 = 6 )\r\nC) It cannot be determined from the given data.\r\nD) ( a_1 + a_2 + a_3 + a_4 + a_5 = 15 )\r\nE) ( a_1 + a_2 + a_3 + a_4 + a_5 = 9 )', 'D'),
(7, 'Rovnice', 'Equations', 'MC: Kvadratická rovnica ( 3x^2 + 2x - 3 = 0 ) má:---\r\nA) Práve jedno riešenie.\r\nB) Práve dve riešenia, ktorých súčin je číslo ( -3 ).\r\nC) Práve dve záporné riešenia.\r\nD) Práve dve riešenia, ktorých súčin je číslo ( -1 ).\r\nE) Práve dve kladné riešenia.', 'MC: The quadratic equation ( 3x^2 + 2x - 3 = 0 ) has:---\r\nA) Exactly one solution.\r\nB) Exactly two solutions with product ( -3 ).\r\nC) Exactly two negative solutions.\r\nD) Exactly two solutions with product ( -1 ).\r\nE) Exactly two positive solutions.', 'D'),
(8, 'Rovnice', 'Equations', 'MC: Výraz ( frac{a^2 - 2ab + b^2}{a^3 - a^2b - ab^2 + b^3} ) sa pre ( a \ne b land a \ne -b ) rovná výrazu:---\r\nA) ( frac{1}{a - b} )\r\nB) Žiadna z ostatných odpovedí nie je správna\r\nC) ( a + b )\r\nD) ( frac{1}{a + b} )\r\nE) ( a - b )', 'MC: The expression ( frac{a^2 - 2ab + b^2}{a^3 - a^2b - ab^2 + b^3} ), for ( a \ne b land a \ne -b ), is equal to:---\r\nA) ( frac{1}{a - b} )\r\nB) None of the other answers is correct\r\nC) ( a + b )\r\nD) ( frac{1}{a + b} )\r\nE) ( a - b )', 'D'),
(9, 'Rovnice', 'Equations', 'MC: Rovnicia ( sqrt{1 + x - 2x^2} = sqrt{x} ) (v ( mathbb{R} ))---\r\nA) nemá žiadne riešenie.\r\nB) má práve dva iracionálne korene.\r\nC) má práve dva korene, ktorých súčin je ( -frac{1}{2} ).\r\nD) má práve jeden celočíselný koreň.\r\nE) má práve jeden koreň.', 'MC: The equation ( sqrt{1 + x - 2x^2} = sqrt{x} ) (in ( mathbb{R} ))---\r\nA) has no solution.\r\nB) has exactly two irrational roots.\r\nC) has exactly two roots whose product is ( -frac{1}{2} ).\r\nD) has exactly one integer root.\r\nE) has exactly one root.', 'E'),
(10, 'Geometria', 'Geometry', 'WA: Dĺžky uhlopriečok kosoštvorca sú 6 a 8 cm. Jeho obvod je (v centimetroch)?', 'WA: The diagonals of a rhombus are 6 cm and 8 cm. Its perimeter is (in centimeters)?', '20'),
(11, 'Kombinatorika', 'Combinatorics', 'MC: Koľko je štvorciferných čísel, ktoré majú vo svojom zápise všetky cifry rôzne?---\r\nA) 9 · 9 · 8 · 7\r\nB) 10 · 9 · 8 · 6\r\nC) 10 · 9 · 8 · 7\r\nD) 9000\r\nE) Žiadna z ostatných odpovedí nie je správna.', 'MC: How many four-digit numbers have all digits different?---\r\nA) 9 · 9 · 8 · 7\r\nB) 10 · 9 · 8 · 6\r\nC) 10 · 9 · 8 · 7\r\nD) 9000\r\nE) None of the other answers is correct.', 'A'),
(12, 'Geometria', 'Geometry', 'MC: Nájdite počet priesečníkov grafu funkcie ( f(x) = x^2 - 2x + 2 ) a priamky ( y = 1 ).---\r\nA) Žiadna z ostatných odpovedí nie je správna.\r\nB) Majú práve tri priesečníky.\r\nC) Majú práve jeden priesečník.\r\nD) Majú práve dva priesečníky.\r\nE) Nemajú žiadny priesečník.', 'MC: Find the number of intersections between the graph of the function ( f(x) = x^2 - 2x + 2 ) and the line ( y = 1 ).---\r\nA) None of the other answers is correct.\r\nB) They intersect at exactly three points.\r\nC) They intersect at exactly one point.\r\nD) They intersect at exactly two points.\r\nE) They do not intersect.', 'C'),
(13, 'Rovnice', 'Equations', 'MC: Množina všetkých riešení rovnice ( sin x = cos x ) je:---\r\nA) ( {kpi; , k in mathbb{Z} } cup left{ frac{pi}{4} + kpi; , k in mathbb{Z} \right} )\r\nB) ( left{ frac{pi}{4} + kpi; , k in mathbb{Z} \right} )\r\nC) ( left{ frac{pi}{4} + 2kpi; , k in mathbb{Z} \right} )\r\nD) ( {kpi; , k in mathbb{Z} } )\r\nE) prázdna množina.', 'MC: The set of all solutions of the equation ( sin x = cos x ) is:---\r\nA) ( {kpi; , k in mathbb{Z} } cup left{ frac{pi}{4} + kpi; , k in mathbb{Z} \right} )\r\nB) ( left{ frac{pi}{4} + kpi; , k in mathbb{Z} \right} )\r\nC) ( left{ frac{pi}{4} + 2kpi; , k in mathbb{Z} \right} )\r\nD) ( {kpi; , k in mathbb{Z} } )\r\nE) the empty set.', 'B'),
(14, 'Algebra', 'Algebra', 'MC: Spoločný menovateľ zlomkov ( frac{x+1}{x-1}, frac{x-1}{x+1}, frac{1}{1+x^2} ) je:---\r\nA) Žiadna z ostatných odpovedí nie je správna.\r\nB) ( 1 - x^2 )\r\nC) ( 1 + x^2 )\r\nD) ( x^4 - 1 )\r\nE) ( x )', 'MC: The least common denominator of the fractions ( frac{x+1}{x-1}, frac{x-1}{x+1}, frac{1}{1+x^2} ) is:---\r\nA) None of the other answers is correct.\r\nB) ( 1 - x^2 )\r\nC) ( 1 + x^2 )\r\nD) ( x^4 - 1 )\r\nE) ( x )', 'D'),
(15, 'Logaritmy', 'Logarithms', 'WA: Ak ( log 3 = a ) a ( log 2 = b ), čomu sa rovná ( log 12 )?', 'WA: If ( log 3 = a ) and ( log 2 = b ), what is the value of ( log 12 )?', 'a + 2b'),
(16, 'Teória čísel', 'Number theory', 'MC: Každý prvok množiny ( M ) je prirodzené číslo, ktoré je deliteľné práve dvoma číslami z trojice čísel 3, 11, 33. Vyberte množinu s touto vlastnosťou.---\r\nA) ( M = {kpi; k in mathbb{Z}} cup {frac{pi}{4} + kpi; k in mathbb{Z}} )\r\nB) ( M = {11, 22, 33} )\r\nC) ( M = {75, 121, 758961} )\r\nD) ( M = {174, 2772, 358479} )\r\nE) ( M = emptyset )', 'MC: Each element of the set ( M ) is a natural number divisible by exactly two numbers from the set {3, 11, 33}. Choose the correct set.---\r\nA) ( M = {kpi; k in mathbb{Z}} cup {frac{pi}{4} + kpi; k in mathbb{Z}} )\r\nB) ( M = {11, 22, 33} )\r\nC) ( M = {75, 121, 758961} )\r\nD) ( M = {174, 2772, 358479} )\r\nE) ( M = emptyset )', 'E'),
(17, 'Rovnice', 'Equations', 'MC: Riešte nerovnicu ( left| frac{x-3}{2x-5} \right| geq 1 ). Množina všetkých jej riešení je:---\r\nA) ( langle 2, frac{8}{3} \rangle )\r\nB) Žiadna z ostatných odpovedí nie je správna.\r\nC) ( langle 2, frac{5}{2} \rangle cup langle frac{5}{2}, frac{8}{3} \rangle )\r\nD) ( langle 2, frac{5}{2} \rangle cup langle frac{5}{2}, frac{8}{3} ) )\r\nE) ( langle 2, frac{5}{2} \rangle )', 'MC: Solve the inequality ( left| frac{x-3}{2x-5} \right| geq 1 ). The set of all its solutions is:---\r\nA) ( langle 2, frac{8}{3} \rangle )\r\nB) None of the other answers is correct.\r\nC) ( langle 2, frac{5}{2} \rangle cup langle frac{5}{2}, frac{8}{3} \rangle )\r\nD) ( langle 2, frac{5}{2} \rangle cup langle frac{5}{2}, frac{8}{3} ) )\r\nE) ( langle 2, frac{5}{2} \rangle )', 'C'),
(18, 'Logika', 'Logic', 'MC: O trojuholníku ( ABC ) je vyslovený výrok: Ak má trojuholník ( ABC ) zhodné uhly pri vrcholoch ( A ) a ( B ), tak je rovnostranný. Negáciou tohto výroku je výrok:---\r\nA) Ak má trojuholník ( ABC ) zhodné uhly pri vrcholoch ( A ) a ( B ), tak je rovnoramenný.\r\nB) Ak je trojuholník ( ABC ) rovnostranný, tak má zhodné uhly pri vrcholoch ( A ) a ( B ).\r\nC) Trojuholník ( ABC ) má zhodné uhly pri vrcholoch ( A ) a ( B ), a nie je rovnostranný.\r\nD) Trojuholník ( ABC ) je rovnostranný a nemá zhodné uhly pri vrcholoch ( A ) a ( B ).\r\nE) Ak má trojuholník ( ABC ) zhodné uhly pri vrcholoch ( A, B ) a ( C ), tak je rovnostranný.', 'MC: A triangle ( ABC ) is described by the statement: If triangle ( ABC ) has equal angles at vertices ( A ) and ( B ), then it is equilateral. The negation of this statement is:---\r\nA) If triangle ( ABC ) has equal angles at vertices ( A ) and ( B ), then it is isosceles.\r\nB) If triangle ( ABC ) is equilateral, then it has equal angles at vertices ( A ) and ( B ).\r\nC) Triangle ( ABC ) has equal angles at vertices ( A ) and ( B ), and is not equilateral.\r\nD) Triangle ( ABC ) is equilateral and does not have equal angles at vertices ( A ) and ( B ).\r\nE) If triangle ( ABC ) has equal angles at vertices ( A ), ( B ), and ( C ), then it is equilateral.', 'C'),
(19, 'Funkcie', 'Functions', 'MC: Je daná lineárna funkcia ( f(x) = 3x - 1 ). Nájdite jej nulové body.---\r\nA) Žiadna z ostatných odpovedí nie je pravdivá.\r\nB) Nemá žiaden nulový bod.\r\nC) Má dva nulové body: 1 a 3\r\nD) Má jeden nulový bod: ( frac{1}{3} )\r\nE) Má jeden nulový bod: 1', 'MC: The linear function ( f(x) = 3x - 1 ) is given. Find its zeros.---\r\nA) None of the other answers is correct.\r\nB) It has no zeros.\r\nC) It has two zeros: 1 and 3\r\nD) It has one zero: ( frac{1}{3} )\r\nE) It has one zero: 1', 'D'),
(20, 'Rovnice', 'Equations', 'MC: Kvadratická rovnica ( 2x^2 + x - 5 = 0 ) má:---\r\nA) Práve jedno riešenie.\r\nB) Práve dve záporné riešenia.\r\nC) Práve dve riešenia, ktorých súčin je číslo (-5).\r\nD) Práve dve riešenia, ktorých súčet je číslo (-frac{1}{2}).\r\nE) Práve dve kladné riešenia.', 'MC: The quadratic equation ( 2x^2 + x - 5 = 0 ) has:---\r\nA) Exactly one solution.\r\nB) Exactly two negative solutions.\r\nC) Exactly two solutions whose product is (-5).\r\nD) Exactly two solutions whose sum is (-frac{1}{2}).\r\nE) Exactly two positive solutions.', 'D'),
(21, 'Rovnice', 'Equations', 'MC: Rovnicia ( sqrt{-x^2 - 2x - 9} = sqrt{x} ) (v ( mathbb{R} ))---\r\nA) má práve jeden celočíselný koreň\r\nB) má práve dva korene, ktorých súčet je ( frac{5}{2} )\r\nC) má práve dva iracionálne korene\r\nD) má práve dva korene, ktorých súčin je ( frac{3}{2} )\r\nE) nemá žiadne riešenie', 'MC: The equation ( sqrt{-x^2 - 2x - 9} = sqrt{x} ) (in ( mathbb{R} ))---\r\nA) has exactly one integer solution\r\nB) has exactly two solutions whose sum is ( frac{5}{2} )\r\nC) has exactly two irrational solutions\r\nD) has exactly two solutions whose product is ( frac{3}{2} )\r\nE) has no solution', 'E'),
(22, 'Rovnice', 'Equations', 'MC: Riešte nerovnicu ( frac{x^2 - 8x + 15}{x + 1} geq 2 ). Množina všetkých jej riešení je---\r\nA) Žiadna z ostatných odpovedí nie je správna.\r\nB) ( left(-infty, 1\right) cup left( frac{3}{2}, infty \right) )\r\nC) ( left( frac{3}{2}, infty \right) )\r\nD) ( (-1, 1) cup left( frac{3}{2}, infty \right) )\r\nE) ( (1, infty) )', 'MC: Solve the inequality ( frac{x^2 - 8x + 15}{x + 1} geq 2 ). The set of all its solutions is---\r\nA) None of the other answers is correct.\r\nB) ( left(-infty, 1\right) cup left( frac{3}{2}, infty \right) )\r\nC) ( left( frac{3}{2}, infty \right) )\r\nD) ( (-1, 1) cup left( frac{3}{2}, infty \right) )\r\nE) ( (1, infty) )', 'D'),
(23, 'Teória čísel', 'Number theory', 'MC: M je množina všetkých dvojciferných prirodzených čísel, ktoré sú deliteľné štyrmi a šiestimi, a nie sú deliteľné ôsmimi. Vyberte množinu M.---\r\nA) ( M = {36, 72} )\r\nB) ( M = {12, 36, 60, 84} )\r\nC) ( M = emptyset )\r\nD) ( M = {12, 24, 36, 48, 60, 72, 84, 96} )\r\nE) ( M = {24, 48, 72, 96} )', 'MC: Let M be the set of all two-digit natural numbers divisible by 4 and 6 but not by 8. Choose the set M.---\r\nA) ( M = {36, 72} )\r\nB) ( M = {12, 36, 60, 84} )\r\nC) ( M = emptyset )\r\nD) ( M = {12, 24, 36, 48, 60, 72, 84, 96} )\r\nE) ( M = {24, 48, 72, 96} )', 'B'),
(24, 'Kombinatorika', 'Combinatorics', 'MC: Koľko je štvorciferných čísel, ktoré majú vo svojom zápise dve párne a dve nepárne cifry? (Nulu považujte za párnu cifru.)---\r\nA) ( 5^3 cdot 4 )\r\nB) ( 5^3 cdot 3^3 )\r\nC) ( 10 cdot 10 cdot 5 cdot 5 )\r\nD) ( 5^4 )\r\nE) Žiadna z ostatných odpovedí nie je správna.', 'MC: How many four-digit numbers contain exactly two even and two odd digits? (Zero is considered even.)---\r\nA) ( 5^3 cdot 4 )\r\nB) ( 5^3 cdot 3^3 )\r\nC) ( 10 cdot 10 cdot 5 cdot 5 )\r\nD) ( 5^4 )\r\nE) None of the other answers is correct.', 'E'),
(25, 'Logaritmy', 'Logarithms', 'MC: Ak ( log 3 = a ) a ( log 4 = b ), čomu sa rovná ( log 6 )?---\r\nA) ( frac{1}{2}ab )\r\nB) ( a + sqrt{b} )\r\nC) ( 3b )\r\nD) ( a + b )\r\nE) ( 2a )', 'MC: If ( log 3 = a ) and ( log 4 = b ), what is ( log 6 )?---\r\nA) ( frac{1}{2}ab )\r\nB) ( a + sqrt{b} )\r\nC) ( 3b )\r\nD) ( a + b )\r\nE) ( 2a )', 'D'),
(26, 'Postupnosti', 'Sequences', 'MC: Nájdite stý člen ( a_{100} ) aritmetickej postupnosti ( {a_n}_{n=1}^{infty} ), ak ( a_{n+1} = a_n - frac{1}{3} ) a ( a_1 = 65 ).---\r\nA) ( a_{100} = -frac{100}{3} )\r\nB) ( a_{100} = 32 )\r\nC) ( a_{100} = frac{95}{3} )\r\nD) ( a_{100} = frac{194}{3} )\r\nE) ( a_{100} = 0 )', 'MC: Find the 100th term ( a_{100} ) of the arithmetic sequence ( {a_n}_{n=1}^{infty} ), given that ( a_{n+1} = a_n - frac{1}{3} ) and ( a_1 = 65 ).---\r\nA) ( a_{100} = -frac{100}{3} )\r\nB) ( a_{100} = 32 )\r\nC) ( a_{100} = frac{95}{3} )\r\nD) ( a_{100} = frac{194}{3} )\r\nE) ( a_{100} = 0 )', 'B'),
(27, 'Geometria', 'Geometry', 'MC: V rovine leží priamka ( p ) a bod ( A ). Vzdialenosť bodu ( A ) od priamky ( p ) je 1. Na priamke ( p ) ležia body ( B ) a ( C ). Trojuholník ( ABC ) je rovnostranný. Aká je dĺžka strany ( BC )?---\r\nA) ( frac{1}{sqrt{3}} )\r\nB) Žiadna z ostatných odpovedí nie je správna.\r\nC) 1\r\nD) ( frac{2}{sqrt{3}} )\r\nE) ( sqrt{3} )', 'MC: In the plane, line ( p ) and point ( A ) are given. The distance from ( A ) to ( p ) is 1. Points ( B ) and ( C ) lie on ( p ). Triangle ( ABC ) is equilateral. What is the length of side ( BC )?---\r\nA) ( frac{1}{sqrt{3}} )\r\nB) None of the other answers is correct.\r\nC) 1\r\nD) ( frac{2}{sqrt{3}} )\r\nE) ( sqrt{3} )', 'D'),
(28, 'Rovnice', 'Equations', 'MC: Rovnica ( 4^x - 2^x = 2 )---\r\nA) nemá žiadne riešenie.\r\nB) má práve jedno riešenie.\r\nC) má práve dve riešenia, ktorých súčet je 1.\r\nD) má práve dve riešenia, ( x = 0 ) a ( x = 1 ).\r\nE) má práve dve riešenia, ktorých súčet je -1.', 'MC: The equation ( 4^x - 2^x = 2 )---\r\nA) has no solution.\r\nB) has exactly one solution.\r\nC) has exactly two solutions whose sum is 1.\r\nD) has exactly two solutions, ( x = 0 ) and ( x = 1 ).\r\nE) has exactly two solutions whose sum is -1.', 'B'),
(29, 'Algebra', 'Algebra', 'MC: Výraz ( frac{1 - sqrt{a}}{1 + sqrt{a}} : frac{1 - a}{1 + a} ) sa pre ( a geq 0,  a \neq 1 ) rovná výrazu:---\r\nA) ( frac{2sqrt{a}}{1 + 2sqrt{a} + a} )\r\nB) ( frac{1 + sqrt{a}}{1 - sqrt{a}} )\r\nC) Žiadna z ostatných odpovedí nie je správna\r\nD) ( frac{1}{1 + a} )\r\nE) ( frac{1}{4} )', 'MC: The expression ( frac{1 - sqrt{a}}{1 + sqrt{a}} : frac{1 - a}{1 + a} ) for ( a geq 0,  a \neq 1 ) equals:---\r\nA) ( frac{2sqrt{a}}{1 + 2sqrt{a} + a} )\r\nB) ( frac{1 + sqrt{a}}{1 - sqrt{a}} )\r\nC) None of the other answers is correct\r\nD) ( frac{1}{1 + a} )\r\nE) ( frac{1}{4} )', 'A'),
(30, 'Algebra', 'Algebra', 'MC: Spoločný menovateľ zlomkov ( frac{x}{x+1},  frac{x-1}{x},  frac{x}{x+2} ) je:---\r\nA) ( x^2 - x - 2 )\r\nB) Žiadna z ostatných odpovedí nie je správna\r\nC) ( x - 2 )\r\nD) ( x )\r\nE) ( x + 1 )', 'MC: The least common denominator of the fractions ( frac{x}{x+1},  frac{x-1}{x},  frac{x}{x+2} ) is:---\r\nA) ( x^2 - x - 2 )\r\nB) None of the other answers is correct\r\nC) ( x - 2 )\r\nD) ( x )\r\nE) ( x + 1 )', 'A'),
(31, 'Geometria', 'Geometry', 'MC: Nájdite počet priesečníkov grafu funkcie ( f(x) = x^2 - 3x + 4 ) a priamky ( y = x ).---\r\nA) Nemajú žiadny priesečník.\r\nB) Majú práve tri priesečníky.\r\nC) Žiadna z ostatných odpovedí nie je správna.\r\nD) Majú práve jeden priesečník.\r\nE) Majú práve dva priesečníky.', 'MC: Find the number of intersections between the graph of the function ( f(x) = x^2 - 3x + 4 ) and the line ( y = x ).---\r\nA) They have no intersection points.\r\nB) They have exactly three intersections.\r\nC) None of the other answers is correct.\r\nD) They have exactly one intersection.\r\nE) They have exactly two intersections.', 'D'),
(32, 'Rovnice', 'Equations', 'MC: Množina všetkých riešení rovnice ( mathrm{tg},x = mathrm{cotg},x ) je---\r\nA) ( {kpi; k in mathbb{Z} } )\r\nB) prázdna množina\r\nC) ( left{ frac{pi}{4} + kpi; k in mathbb{Z} \right} )\r\nD) ( left{ frac{pi}{4} + kpi; k in mathbb{Z} \right} cup left{ frac{3pi}{4} + kpi; k in mathbb{Z} \right} )\r\nE) ( left{ frac{3pi}{4} + kpi; k in mathbb{Z} \right} )', 'MC: The set of all solutions of the equation ( 	an x = cot x ) is---\r\nA) ( {kpi; k in mathbb{Z} } )\r\nB) the empty set\r\nC) ( left{ frac{pi}{4} + kpi; k in mathbb{Z} \right} )\r\nD) ( left{ frac{pi}{4} + kpi; k in mathbb{Z} \right} cup left{ frac{3pi}{4} + kpi; k in mathbb{Z} \right} )\r\nE) ( left{ frac{3pi}{4} + kpi; k in mathbb{Z} \right} )', 'C'),
(33, 'Rovnice', 'Equations', 'MC: Riešením rovnice ( log_{x-1} 8 = 3 ) je---\nA) ( x = 3 )\nB) ( x = 1 )\nC) ( x = 2 )\nD) ( x = 4 )\nE) ( x = 5 )', 'MC: The solution of the equation ( log_{x-1} 8 = 3 ) is---\nA) ( x = 3 )\nB) ( x = 1 )\nC) ( x = 2 )\nD) ( x = 4 )\nE) ( x = 5 )', 'A'),
(34, 'Rovnice', 'Equations', 'MC: Riešením rovnice ( frac{1}{5^{x-1}} = 25 ) je---\nA) ( x = -1 )\nB) ( x = 1 )\nC) ( x = 2 )\nD) ( x = 0 )\nE) ( x = 3 )', 'MC: The solution of the equation ( frac{1}{5^{x-1}} = 25 ) is---\nA) ( x = -1 )\nB) ( x = 1 )\nC) ( x = 2 )\nD) ( x = 0 )\nE) ( x = 3 )', 'A'),
(35, 'Algebra', 'Algebra', 'MC: Spoločný menovateľ zlomkov ( frac{x}{x-2}, frac{x}{x+2} ) je---\nA) ( x + 2 )\nB) ( x^2 )\nC) ( x^2 - 4 )\nD) ( x - 2 )\nE) Žiadna z ostatných odpovedí nie je správna', 'MC: The least common denominator of fractions ( frac{x}{x-2}, frac{x}{x+2} ) is---\nA) ( x + 2 )\nB) ( x^2 )\nC) ( x^2 - 4 )\nD) ( x - 2 )\nE) None of the other answers is correct', 'C'),
(36, 'Rovnice', 'Equations', 'MC: Kvadratický trojčlen ( 3x^2 + 9x - 12 ) má rozklad---\nA) ( 3(x + 1)(x - 4) )\nB) ( (x - 3)(x + 4) )\nC) ( (x + 1)(x + 4) )\nD) ( 3(x + 4)(x - 1) )\nE) ( 3(x - 2)(x + 2) )', 'MC: The quadratic trinomial ( 3x^2 + 9x - 12 ) factors as---\nA) ( 3(x + 1)(x - 4) )\nB) ( (x - 3)(x + 4) )\nC) ( (x + 1)(x + 4) )\nD) ( 3(x + 4)(x - 1) )\nE) ( 3(x - 2)(x + 2) )', 'D'),
(37, 'Rovnice', 'Equations', 'MC: Riešenie nerovnice ( frac{1 - x}{x + 5} geq 2 ) je---\nA) ( (-5, -3) )\nB) Žiadna z ostatných odpovedí nie je správna\nC) ( (-infty, -5) cup (-3, infty) )\nD) ( (-infty, -5) cup (-3, 0) )\nE) ( (-5, -3) )', 'MC: The solution of the inequality ( frac{1 - x}{x + 5} geq 2 ) is---\nA) ( (-5, -3) )\nB) None of the other answers is correct\nC) ( (-infty, -5) cup (-3, infty) )\nD) ( (-infty, -5) cup (-3, 0) )\nE) ( (-5, -3) )', 'C'),
(38, 'Funkcie', 'Functions', 'MC: Funkcia ( f(x) = log(3 - x) ) má definičný obor---\nA) ( (-3, 3) )\nB) ( (-infty, -3) )\nC) ( (-infty, 3) )\nD) ( (-infty, 0) )\nE) ( (-3, 0) )', 'MC: The function ( f(x) = log(3 - x) ) has a domain---\nA) ( (-3, 3) )\nB) ( (-infty, -3) )\nC) ( (-infty, 3) )\nD) ( (-infty, 0) )\nE) ( (-3, 0) )', 'C'),
(39, 'Logika', 'Logic', 'MC: Z výroku: Bod A nie je priesečníkom priamok ( p ) a ( q ), vyplýva---\nA) Bod A neleží na priamke ( p ) alebo ( q )\nB) Bod A neleží ani na priamke ( p ), ani ( q )\nC) Priamky ( p ) a ( q ) sú rovnobežné\nD) Buď ( p ) alebo ( q ) nie je priamka\nE) Priamky ( p ) a ( q ) majú iný priesečník', 'MC: From the statement: Point A is not the intersection of lines ( p ) and ( q ), it follows---\nA) Point A is not on line ( p ) or ( q )\nB) Point A is on neither line ( p ) nor ( q )\nC) Lines ( p ) and ( q ) are parallel\nD) Either ( p ) or ( q ) is not a line\nE) Lines ( p ) and ( q ) intersect elsewhere', 'A'),
(40, 'Rovnice', 'Equations', 'MC: Riešenie rovnice ( 2^{x+1} = 4^{x-3} ) patrí do---\nA) množiny ( (-infty, 0) cup (0, infty) )\nB) intervalu ( (2, 3) )\nC) intervalu ( (1, 2) )\nD) intervalu ( (0, 1) )\nE) intervalu ( (1, infty) )', 'MC: The solution to the equation ( 2^{x+1} = 4^{x-3} ) belongs to---\nA) set ( (-infty, 0) cup (0, infty) )\nB) interval ( (2, 3) )\nC) interval ( (1, 2) )\nD) interval ( (0, 1) )\nE) interval ( (1, infty) )', 'B'),
(41, 'Algebra', 'Algebra', 'MC: Výraz ( left( frac{1}{a} + 1 \right) : left( a + 2 + frac{1 - 2(a+1)^2}{a} \right) ) sa pre ( a \neq 0 ), ( a \neq -1 ) rovná výrazu---\nA) Žiadna z ostatných odpovedí nie je správna\nB) ( frac{1}{2a} )\nC) ( frac{1}{a} )\nD) ( frac{1}{2} )\nE) ( frac{1}{1 + a} )', 'MC: The expression ( left( frac{1}{a} + 1 \right) : left( a + 2 + frac{1 - 2(a+1)^2}{a} \right) ) for ( a \neq 0 ), ( a \neq -1 ) equals---\nA) None of the other answers is correct\nB) ( frac{1}{2a} )\nC) ( frac{1}{a} )\nD) ( frac{1}{2} )\nE) ( frac{1}{1 + a} )', 'D'),
(42, 'Funkcie', 'Functions', 'MC: Lineárna funkcia ( f(x) = 3x + 1 )---\nA) má práve jeden nulový bod, a to ( frac{1}{3} )\nB) má práve jeden nulový bod, a to 1\nC) má dva nulové body, a to ( frac{1}{3} ) a 1\nD) Žiadna z ostatných odpovedí nie je pravdivá\nE) nemá žiadny nulový bod', 'MC: The linear function ( f(x) = 3x + 1 )---\nA) has exactly one zero, namely ( frac{1}{3} )\nB) has exactly one zero, namely 1\nC) has two zeros, ( frac{1}{3} ) and 1\nD) None of the other answers is correct\nE) has no zeros', 'D'),
(43, 'Rovnice', 'Equations', 'MC: Rovnicia ( |x - 2| = 5 ) má množinu riešení---\nA) {1, 5}\nB) {7}\nC) {-3, 7}\nD) {-3, 7}\nE) {-7, 3}', 'MC: The equation ( |x - 2| = 5 ) has the solution set---\nA) {1, 5}\nB) {7}\nC) {-3, 7}\nD) {-3, 7}\nE) {-7, 3}', 'C'),
(44, 'Funkcie', 'Functions', 'MC: Graf funkcie ( f(x) = 3x^2 - 5x + 2 )---\nA) leží celý nad osou x\nB) leží celý pod osou x\nC) žiadna z ostatných odpovedí nie je správna\nD) pretína os x v dvoch bodoch\nE) sa dotýka osi x v jednom bode', 'MC: The graph of the function ( f(x) = 3x^2 - 5x + 2 )---\nA) lies entirely above the x-axis\nB) lies entirely below the x-axis\nC) none of the other answers is correct\nD) intersects the x-axis in two points\nE) touches the x-axis in one point', 'D'),
(45, 'Kombinatorika', 'Combinatorics', 'MC: Koľkými spôsobmi sa dá rozdeliť pravidelný šesťuholník ( ABCDEF ) na štyri neprekrývajúce sa trojuholníky?---\nA) Práve šiestimi\nB) Práve dvanástimi\nC) Práve trinástimi\nD) Práve osemnástimi\nE) Žiadna z ostatných odpovedí nie je správna', 'MC: In how many ways can a regular hexagon ( ABCDEF ) be divided into four non-overlapping triangles?---\nA) Exactly six\nB) Exactly twelve\nC) Exactly thirteen\nD) Exactly eighteen\nE) None of the other answers is correct', 'B'),
(46, 'Rovnice', 'Equations', 'MC: Množina riešení rovnice ( 2 sin x = 	an x ) je---\nA) ( left{ frac{pi}{3} + kpi; k in mathbb{Z} \right} )\nB) ( left{ kpi; k in mathbb{Z} \right} cup left{ frac{pi}{3} + kpi; k in mathbb{Z} \right} )\nC) Rovnica nemá riešenie\nD) ( left{ x in mathbb{R}; x = frac{pi}{3} + 2kpi; k in mathbb{Z} \right} cup left{ x = -frac{pi}{3} + 2kpi; k in mathbb{Z} \right} )\nE) ( left{ frac{pi}{3}; k in mathbb{Z} \right} )', 'MC: The solution set of the equation ( 2 sin x = 	an x ) is---\nA) ( left{ frac{pi}{3} + kpi; k in mathbb{Z} \right} )\nB) ( left{ kpi; k in mathbb{Z} \right} cup left{ frac{pi}{3} + kpi; k in mathbb{Z} \right} )\nC) The equation has no solution\nD) ( left{ x in mathbb{R}; x = frac{pi}{3} + 2kpi; k in mathbb{Z} \right} cup left{ x = -frac{pi}{3} + 2kpi; k in mathbb{Z} \right} )\nE) ( left{ frac{pi}{3}; k in mathbb{Z} \right} )', 'D'),
(47, 'Geometria', 'Geometry', 'MC: V rovine ležia dva trojuholníky. Ich prienik je úsečka. Ich zjednotením je:---\nA) Trojuholník alebo štvoruholník\nB) Trojuholník, štvoruholník, päťuholník alebo šesťuholník\nC) Trojuholník, štvoruholník alebo päťuholník\nD) Trojuholník\nE) Štvoruholník', 'MC: Two triangles lie in a plane. Their intersection is a segment. Their union is:---\nA) Triangle or quadrilateral\nB) Triangle, quadrilateral, pentagon or hexagon\nC) Triangle, quadrilateral or pentagon\nD) Triangle\nE) Quadrilateral', 'C'),
(48, 'Algebra', 'Algebra', 'MC: Výraz ( left( frac{x^2}{y^2} - frac{x}{y} \right) left( frac{x^2 + y^2}{xy} - 2 \right)^{-1} frac{y^2}{x^2} left( frac{1}{y} - frac{1}{x} \right) ) sa rovná:---\r\nA) ( frac{1}{x}, quad x \ne 0, y \ne 0, y \ne x )\r\nB) ( 1, quad x \ne 0, y \ne 0 )\r\nC) ( -frac{1}{x}, quad x \ne 0, y \ne 0, y \ne x )\r\nD) ( frac{1}{x}, quad x \ne 0, y \ne 0 )\r\nE) ( x, quad x \ne 0, y \ne 0, y \ne x )', 'MC: The expression ( left( frac{x^2}{y^2} - frac{x}{y} \right) left( frac{x^2 + y^2}{xy} - 2 \right)^{-1} frac{y^2}{x^2} left( frac{1}{y} - frac{1}{x} \right) ) equals:---\r\nA) ( frac{1}{x}, quad x \ne 0, y \ne 0, y \ne x )\r\nB) ( 1, quad x \ne 0, y \ne 0 )\r\nC) ( -frac{1}{x}, quad x \ne 0, y \ne 0, y \ne x )\r\nD) ( frac{1}{x}, quad x \ne 0, y \ne 0 )\r\nE) ( x, quad x \ne 0, y \ne 0, y \ne x )', 'C'),
(49, 'Algebra', 'Algebra', 'MC: Výraz ( frac{sqrt{a} + sqrt{b} + sqrt{a} - sqrt{b}}{a - b} cdot frac{a + 2sqrt{ab} + b - 2sqrt{ab} - 2b}{a + 2sqrt{ab} + b - a + 2sqrt{ab} - b} ) sa rovná:---\r\nA) ( sqrt{a} - sqrt{b}, a > 0, b > 0 )\r\nB) ( frac{1}{sqrt{a} + sqrt{b}}, a \ne 0, b \ne 0 )\r\nC) ( frac{1}{a + b}, a \ne b, a \ne -b )\r\nD) ( frac{sqrt{a}}{2sqrt{b}}, a > 0, b > 0, a \ne b )\r\nE) ( frac{1}{2sqrt{b}}, a > 0, b > 0, a \ne b )', 'MC: The expression ( frac{sqrt{a} + sqrt{b} + sqrt{a} - sqrt{b}}{a - b} cdot frac{a + 2sqrt{ab} + b - 2sqrt{ab} - 2b}{a + 2sqrt{ab} + b - a + 2sqrt{ab} - b} ) equals:---\r\nA) ( sqrt{a} - sqrt{b}, a > 0, b > 0 )\r\nB) ( frac{1}{sqrt{a} + sqrt{b}}, a \ne 0, b \ne 0 )\r\nC) ( frac{1}{a + b}, a \ne b, a \ne -b )\r\nD) ( frac{sqrt{a}}{2sqrt{b}}, a > 0, b > 0, a \ne b )\r\nE) ( frac{1}{2sqrt{b}}, a > 0, b > 0, a \ne b )', 'E'),
(50, 'Algebra', 'Algebra', 'MC: Výraz ( left( frac{2x}{x+y} - frac{3y}{x - y} - frac{2x^2 - 3y^2}{x^2 - y^2} \right)^{-1} cdot frac{x - y}{y} cdot frac{5x}{x + y} ) sa rovná:---\r\nA) ( y, x \ne 0, y \ne 0, x \ne y )\r\nB) ( 1, x \ne 0, y \ne 0, y \ne x, y \ne -x )\r\nC) ( -x, x \ne 0, y \ne x, y \ne -x )\r\nD) ( -1, x \ne 0, y \ne 0, y \ne x )\r\nE) ( x, x \ne 0, y \ne 0, y \ne x, y \ne -x )', 'MC: The expression ( left( frac{2x}{x+y} - frac{3y}{x - y} - frac{2x^2 - 3y^2}{x^2 - y^2} \right)^{-1} cdot frac{x - y}{y} cdot frac{5x}{x + y} ) equals:---\r\nA) ( y, x \ne 0, y \ne 0, x \ne y )\r\nB) ( 1, x \ne 0, y \ne 0, y \ne x, y \ne -x )\r\nC) ( -x, x \ne 0, y \ne x, y \ne -x )\r\nD) ( -1, x \ne 0, y \ne 0, y \ne x )\r\nE) ( x, x \ne 0, y \ne 0, y \ne x, y \ne -x )', 'B'),
(51, 'Algebra', 'Algebra', 'MC: Výraz ( left( frac{a}{a + b} - frac{b}{b - a} - frac{2ab}{a^2 - b^2} \right) cdot left( a - frac{4ab}{a + b} + b \right)^{-1} ) sa rovná:---\r\nA) ( frac{1}{a - b}, a \ne b, a \ne -b )\r\nB) ( frac{1}{a + b}, a \ne b, a \ne -b )\r\nC) ( a - b, a \ne b, a \ne -b )\r\nD) ( frac{1}{a + b}, a \ne 0, b \ne 0 )\r\nE) ( a + b, a \ne b, a \ne -b )', 'MC: The expression ( left( frac{a}{a + b} - frac{b}{b - a} - frac{2ab}{a^2 - b^2} \right) cdot left( a - frac{4ab}{a + b} + b \right)^{-1} ) equals:---\r\nA) ( frac{1}{a - b}, a \ne b, a \ne -b )\r\nB) ( frac{1}{a + b}, a \ne b, a \ne -b )\r\nC) ( a - b, a \ne b, a \ne -b )\r\nD) ( frac{1}{a + b}, a \ne 0, b \ne 0 )\r\nE) ( a + b, a \ne b, a \ne -b )', 'B'),
(52, 'Algebra', 'Algebra', 'MC: Nech ( a > 0, 0 < b < frac{1}{2} ), výraz ( left( a + sqrt{a^2 - frac{4a^2b^2}{(b^2 + 1)^2}} \right) cdot left( frac{b^2 + 1}{2ab} \right)^{-1} ) sa rovná:---\r\nA) ( frac{1}{b} )\r\nB) ( b )\r\nC) ( -1 )\r\nD) ( 1 )\r\nE) ( frac{1}{b^2} )', 'MC: Let ( a > 0, 0 < b < frac{1}{2} ), the expression ( left( a + sqrt{a^2 - frac{4a^2b^2}{(b^2 + 1)^2}} \right) cdot left( frac{b^2 + 1}{2ab} \right)^{-1} ) equals:---\r\nA) ( frac{1}{b} )\r\nB) ( b )\r\nC) ( -1 )\r\nD) ( 1 )\r\nE) ( frac{1}{b^2} )', 'A'),
(53, 'Algebra', 'Algebra', 'MC: Kvadratický trojčlen ( 30x^2 + 11x - 30 ) sa dá v ( mathbb{R} ) rozložiť na súčin lineárnych činiteľov:---\r\nA) ( left(x - frac{5}{6}\right)left(x + frac{6}{5}\right) )\r\nB) sa nedá v ( mathbb{R} ) rozložiť\r\nC) ( 30left(x - frac{5}{6}\right)left(x + frac{6}{5}\right) )\r\nD) ( 30left(x - frac{5}{6}\right)left(x + frac{2}{5}\right) )\r\nE) ( left(x - frac{4}{6}\right)left(x + frac{6}{5}\right) )', 'MC: The quadratic trinomial ( 30x^2 + 11x - 30 ) can be factored in ( mathbb{R} ) as a product of linear factors:---\r\nA) ( left(x - frac{5}{6}\right)left(x + frac{6}{5}\right) )\r\nB) cannot be factored in ( mathbb{R} )\r\nC) ( 30left(x - frac{5}{6}\right)left(x + frac{6}{5}\right) )\r\nD) ( 30left(x - frac{5}{6}\right)left(x + frac{2}{5}\right) )\r\nE) ( left(x - frac{4}{6}\right)left(x + frac{6}{5}\right) )', 'C'),
(54, 'Rovnice', 'Equations', 'MC: Množina koreňov rovnice ( 3left(sqrt{x^2 + 13} - sqrt{x^2 - 11}\right) = x ) sa rovná:---\r\nA) ( K = {6} )\r\nB) ( K = {5} )\r\nC) ( K = {-2, 7} )\r\nD) ( K = {-6, 6} )\r\nE) ( K = {-6} )', 'MC: The solution set of the equation ( 3left(sqrt{x^2 + 13} - sqrt{x^2 - 11}\right) = x ) is:---\r\nA) ( K = {6} )\r\nB) ( K = {5} )\r\nC) ( K = {-2, 7} )\r\nD) ( K = {-6, 6} )\r\nE) ( K = {-6} )', 'D'),
(55, 'Rovnice', 'Equations', 'MC: Riešenie rovnice ( frac{1}{sqrt{x} + 10} = frac{1}{sqrt{25 - 2sqrt{x}}} ) v ( mathbb{R} ) sa rovná:---\r\nA) ( K = {25} )\r\nB) ( K = {-4} )\r\nC) ( K = {9} )\r\nD) ( K = {125} )\r\nE) ( K = {16} )', 'MC: The solution of the equation ( frac{1}{sqrt{x} + 10} = frac{1}{sqrt{25 - 2sqrt{x}}} ) in ( mathbb{R} ) is:---\r\nA) ( K = {25} )\r\nB) ( K = {-4} )\r\nC) ( K = {9} )\r\nD) ( K = {125} )\r\nE) ( K = {16} )', 'C'),
(56, 'Rovnice', 'Equations', 'MC: Výraz ( frac{sqrt{frac{2x - 1}{x + 1}} - 1}{sqrt{x + 1}} ) má zmysel pre ( x in mathbb{R} ):---\r\nA) ( P = mathbb{R} )\r\nB) ( P = (-infty, 1) cup (2, infty) )\r\nC) ( P = (-infty, -1) )\r\nD) ( P = (-infty, -1) cup (2, infty) )\r\nE) ( P = (2, infty) )', 'MC: The expression ( frac{sqrt{frac{2x - 1}{x + 1}} - 1}{sqrt{x + 1}} ) is defined for ( x in mathbb{R} ):---\r\nA) ( P = mathbb{R} )\r\nB) ( P = (-infty, 1) cup (2, infty) )\r\nC) ( P = (-infty, -1) )\r\nD) ( P = (-infty, -1) cup (2, infty) )\r\nE) ( P = (2, infty) )', 'D'),
(57, 'Rovnice', 'Equations', 'MC: Riešením nerovnice ( sqrt{x} - 3 < frac{2}{sqrt{x} - 2} ) v ( mathbb{R} ) je:---\r\nA) ( P = (4, 16) )\r\nB) ( P = (0, 1) cup (4, 16) )\r\nC) ( P = (0, 4) )\r\nD) ( P = (0, 16) )\r\nE) ( P = (0, 4) cup (4, 16) )', 'MC: The solution of the inequality ( sqrt{x} - 3 < frac{2}{sqrt{x} - 2} ) in ( mathbb{R} ) is:---\r\nA) ( P = (4, 16) )\r\nB) ( P = (0, 1) cup (4, 16) )\r\nC) ( P = (0, 4) )\r\nD) ( P = (0, 16) )\r\nE) ( P = (0, 4) cup (4, 16) )', 'E'),
(58, 'Rovnice', 'Equations', 'MC: Riešením nerovnice ( sqrt{x} + 2x^2 leq (x+1)^2 + 1 ) v ( mathbb{N} ) je:---\r\nA) ( P = {0, 2} )\r\nB) ( P = {1, 2} )\r\nC) ( P = {0} )\r\nD) ( P = {0, 1, 2} )\r\nE) ( P = (0, 2) )', 'MC: The solution of the inequality ( sqrt{x} + 2x^2 leq (x+1)^2 + 1 ) in ( mathbb{N} ) is:---\r\nA) ( P = {0, 2} )\r\nB) ( P = {1, 2} )\r\nC) ( P = {0} )\r\nD) ( P = {0, 1, 2} )\r\nE) ( P = (0, 2) )', 'D'),
(59, 'Rovnice', 'Equations', 'MC: Riešením nerovnice ( x - 1 < sqrt{7 - x} ) v ( mathbb{R} ) je:---\r\nA) ( P = (-infty, 1) )\r\nB) ( P = (-2, 3) )\r\nC) ( P = (1, 3) )\r\nD) ( P = (-infty, 3) )\r\nE) ( P = (-2, 3) )', 'MC: The solution of the inequality ( x - 1 < sqrt{7 - x} ) in ( mathbb{R} ) is:---\r\nA) ( P = (-infty, 1) )\r\nB) ( P = (-2, 3) )\r\nC) ( P = (1, 3) )\r\nD) ( P = (-infty, 3) )\r\nE) ( P = (-2, 3) )', 'B'),
(60, 'Geometria', 'Geometry', 'MC: Objem pravidelného trojbokého ihlana s dĺžkou hrany ( a ), vyjadrený ako funkcia jeho povrchu ( S ), je:---\r\nA) ( V = 4S )\r\nB) ( V = frac{sqrt{3}}{12 cdot (sqrt{3})^3} cdot S^{frac{3}{2}} )\r\nC) ( V = frac{1}{3} cdot S^{frac{3}{2}} )\r\nD) ( V = 3S )\r\nE) nevieme vyjadriť', 'MC: The volume of a regular triangular pyramid with edge length ( a ), expressed as a function of surface area ( S ), is:---\r\nA) ( V = 4S )\r\nB) ( V = frac{sqrt{3}}{12 cdot (sqrt{3})^3} cdot S^{frac{3}{2}} )\r\nC) ( V = frac{1}{3} cdot S^{frac{3}{2}} )\r\nD) ( V = 3S )\r\nE) Cannot be expressed', 'B'),
(61, 'Funkcie', 'Functions', 'MC: Definičný obor funkcie ( f(x) = logleft(sqrt{x^2 - 9} - x\right) ) je:---\r\nA) ( D(f) = (-infty, -3) cup (3, infty) )\r\nB) ( D(f) = (-infty, -3) )\r\nC) ( D(f) = (-3, 3) )\r\nD) ( D(f) = (-3, 0) )\r\nE) ( D(f) = langle -3, 3 \rangle )', 'MC: The domain of the function ( f(x) = logleft(sqrt{x^2 - 9} - x\right) ) is:---\r\nA) ( D(f) = (-infty, -3) cup (3, infty) )\r\nB) ( D(f) = (-infty, -3) )\r\nC) ( D(f) = (-3, 3) )\r\nD) ( D(f) = (-3, 0) )\r\nE) ( D(f) = langle -3, 3 \rangle )', 'A'),
(62, 'Funkcie', 'Functions', 'MC: Funkcia ( f(x) = 10^{2x - 3} ) má inverznú funkciu---\r\nA) ( f^{-1}(x) = cos(sqrt{2}) + frac{3}{2} )\r\nB) ( f^{-1}(x) = e^{x^2} + frac{3}{2} )\r\nC) nemá inverznú funkciu\r\nD) ( f^{-1}(x) = frac{1}{2} ln x + frac{3}{2} )\r\nE) ( f^{-1}(x) = log(sqrt{2}) + frac{3}{2} )', 'MC: The function ( f(x) = 10^{2x - 3} ) has an inverse function---\r\nA) ( f^{-1}(x) = cos(sqrt{2}) + frac{3}{2} )\r\nB) ( f^{-1}(x) = e^{x^2} + frac{3}{2} )\r\nC) does not have an inverse function\r\nD) ( f^{-1}(x) = frac{1}{2} ln x + frac{3}{2} )\r\nE) ( f^{-1}(x) = log(sqrt{2}) + frac{3}{2} )', 'D'),
(63, 'Goniometria', 'Trigonometry', 'MC: Ak ( sin z = -frac{5}{13} ), ( pi < z < frac{3pi}{2} ), potom---\r\nA) ( cos z = -frac{11}{13} )\r\nB) ( cos z = -frac{12}{13} )\r\nC) ( cos z = frac{11}{13} )\r\nD) ( cos z = -frac{3}{2} )\r\nE) ( cos z = frac{12}{13} )', 'MC: If ( sin z = -frac{5}{13} ), ( pi < z < frac{3pi}{2} ), then---\r\nA) ( cos z = -frac{11}{13} )\r\nB) ( cos z = -frac{12}{13} )\r\nC) ( cos z = frac{11}{13} )\r\nD) ( cos z = -frac{3}{2} )\r\nE) ( cos z = frac{12}{13} )', 'A'),
(64, 'Rovnice', 'Equations', 'MC: Riešte rovnicu ( log_4(z + 12) - log_4 2 = 1 ) v ( mathbb{R} )---\r\nA) ( K = {0} )\r\nB) ( K = {4} )\r\nC) ( K = emptyset )\r\nD) Žiadna z uvedených možností\r\nE) ( K = {-3, 4} )', 'MC: Solve the equation ( log_4(z + 12) - log_4 2 = 1 ) in ( mathbb{R} )---\r\nA) ( K = {0} )\r\nB) ( K = {4} )\r\nC) ( K = emptyset )\r\nD) None of the options\r\nE) ( K = {-3, 4} )', 'B'),
(65, 'Rovnice', 'Equations', 'MC: Riešte rovnicu ( 0.25^{x - 2} = frac{256}{x^2 - 3} ) a nájdite interval, v ktorom sa nachádza jej riešenie---\r\nA) ( (3, 5) )\r\nB) ( (0, 3) )\r\nC) Žiadna z uvedených možností\r\nD) ( (-3, 0) )\r\nE) ( (5, 7) )', 'MC: Solve the equation ( 0.25^{x - 2} = frac{256}{x^2 - 3} ) and find the interval containing its solution---\r\nA) ( (3, 5) )\r\nB) ( (0, 3) )\r\nC) None of the options\r\nD) ( (-3, 0) )\r\nE) ( (5, 7) )', 'A'),
(66, 'Rovnice', 'Equations', 'MC: Množina riešení rovnice ( sqrt{100^x cdot sqrt{x}} = 10 ) v ( mathbb{R} ) je---\r\nA) ( K = {0, 0{,}01; 100} )\r\nB) ( K = {0,01} )\r\nC) ( K = {100} )\r\nD) ( K = emptyset )\r\nE) ( K = {-100; 0; 0{,}01} )', 'MC: The solution set of the equation ( sqrt{100^x cdot sqrt{x}} = 10 ) in ( mathbb{R} ) is---\r\nA) ( K = {0, 0.01; 100} )\r\nB) ( K = {0.01} )\r\nC) ( K = {100} )\r\nD) ( K = emptyset )\r\nE) ( K = {-100; 0; 0.01} )', 'A'),
(67, 'Rovnice', 'Equations', 'MC: Riešením rovnice ( frac{cos 2x}{cos^2 x} = 1 - frac{2 sin^2 x}{sin(2x)} ) v ( mathbb{R} ) je---\r\nA) ( K = {2kpi, frac{pi}{4} + kpi; k in mathbb{Z}} )\r\nB) ( K = {kpi, frac{pi}{4} + 2kpi; k in mathbb{Z}} )\r\nC) ( K = {frac{pi}{4} + kpi; k in mathbb{Z}} )\r\nD) ( K = {frac{pi}{4} + 2kpi; k in mathbb{Z}} )\r\nE) ( K = {kpi, frac{pi}{4} + kpi; k in mathbb{Z}} )', 'MC: The solution set of the equation ( frac{cos 2x}{cos^2 x} = 1 - frac{2 sin^2 x}{sin(2x)} ) in ( mathbb{R} ) is---\r\nA) ( K = {2kpi, frac{pi}{4} + kpi; k in mathbb{Z}} )\r\nB) ( K = {kpi, frac{pi}{4} + 2kpi; k in mathbb{Z}} )\r\nC) ( K = {frac{pi}{4} + kpi; k in mathbb{Z}} )\r\nD) ( K = {frac{pi}{4} + 2kpi; k in mathbb{Z}} )\r\nE) ( K = {kpi, frac{pi}{4} + kpi; k in mathbb{Z}} )', 'E'),
(68, 'Postupnosti', 'Sequences', 'MC: Prvý člen a diferencia aritmetickej postupnosti, pre ktorú platí ( 3a_1 - a_4 = 0 ), ( a_6 - a_2 = 6 ), sa rovnajú---\r\nA) ( a_1 = 3, d = 1 )\r\nB) ( a_1 = 0, d = 2 )\r\nC) ( a_1 = 2, d = 3 )\r\nD) ( a_1 = 3, d = -1 )\r\nE) ( a_1 = 3, d = 2 )', 'MC: The first term and difference of the arithmetic sequence that satisfies ( 3a_1 - a_4 = 0 ), ( a_6 - a_2 = 6 ), are---\r\nA) ( a_1 = 3, d = 1 )\r\nB) ( a_1 = 0, d = 2 )\r\nC) ( a_1 = 2, d = 3 )\r\nD) ( a_1 = 3, d = -1 )\r\nE) ( a_1 = 3, d = 2 )', 'A'),
(69, 'Postupnosti', 'Sequences', 'MC: Prvý člen a kvocient geometrickej postupnosti, pre ktorú platí ( a_1 - 2a_5 = 9 ), ( a_1 cdot a_5 = 2916 ), sa rovnajú---\r\nA) ( a_1 = -64, q = frac{2}{3} )\r\nB) ( a_1 = -36, q = frac{2}{3} )\r\nC) ( a_1 = 64, q = frac{2}{3} )\r\nD) ( a_1 = 81, q = frac{3}{4} )\r\nE) ( a_1 = -36, q = frac{3}{4} )', 'MC: The first term and ratio of the geometric sequence that satisfies ( a_1 - 2a_5 = 9 ), ( a_1 cdot a_5 = 2916 ), are---\r\nA) ( a_1 = -64, q = frac{2}{3} )\r\nB) ( a_1 = -36, q = frac{2}{3} )\r\nC) ( a_1 = 64, q = frac{2}{3} )\r\nD) ( a_1 = 81, q = frac{3}{4} )\r\nE) ( a_1 = -36, q = frac{3}{4} )', 'B'),
(70, 'Postupnosti', 'Sequences', 'WA: Veža je postavená tak, že nasledujúce poschodie má \\( \\frac{9}{10} \\) výšky predchádzajúceho poschodia. Najmenej koľko poschodí treba vystavať, aby výška veže bola väčšia ako \\( 25 \\text{ m} \\), ak prvé poschodie má výšku \\( 5 \\text{ m} \\)?', 'WA: A tower is built so that each next floor is \\( \\frac{9}{10} \\) the height of the previous one. What is the minimum number of floors needed so that the tower\'s total height exceeds \\( 25 \\text{ m} \\), if the first floor is \\( 5 \\text{ m} \\) high?', '7'),
(71, 'Kombinatorika', 'Combinatorics', 'MC: Počet prirodzených čísel menších ako ( 10^4 ), ktorých cifry sú navzájom rôzne sa rovná.---\r\nA) 5274\r\nB) 4536\r\nC) 5860\r\nD) žiadna z uvedených možností\r\nE) 385', 'MC: The number of natural numbers less than ( 10^4 ), whose digits are all different, is equal to.---\r\nA) 5274\r\nB) 4536\r\nC) 5860\r\nD) none of the above\r\nE) 385', 'B'),
(72, 'Kombinatorika', 'Combinatorics', 'MC: Trezor má zámok s piatimi kotúčmi, na ktorých sú čísla ( 0, 1, 2, 3, ldots, 9 ). Zámok sa otvorí na heslo, ktorým je správna voľba ľubovoľnej cifry na každom z kotúčov. Pokladník zabudol heslo, pamätá si len, že na prvom mieste nebola cifra 0 ani cifra 1. Počet možností pre vyskúšanie správnej kombinácie čísel sa rovná.---\r\nA) ( 8 cdot 10^4 )\r\nB) ( 8 cdot inom{10}{4} )\r\nC) ( 9 cdot 10^3 )\r\nD) ( 10^5 )\r\nE) ( 99 cdot 10^3 )', 'MC: A lock has five dials with numbers ( 0, 1, 2, 3, ldots, 9 ). The lock opens with a correct combination of any digits on the dials. The cashier forgot the code but remembers the first digit was neither 0 nor 1. The number of possible combinations to try is equal to.---\r\nA) ( 8 cdot 10^4 )\r\nB) ( 8 cdot inom{10}{4} )\r\nC) ( 9 cdot 10^3 )\r\nD) ( 10^5 )\r\nE) ( 99 cdot 10^3 )', 'A'),
(73, 'Kombinatorika', 'Combinatorics', 'MC: Trom deťom možno rozdeliť ( 7 ) rovnakých čokolád a ( 5 ) rovnakých balíčkov cukríkov ( p )-spôsobmi, kde ( p ) sa rovná.---\r\nA) ( p = C^{r}(3,7) cdot C^{r}(3,5) = 2940 )\r\nB) ( p = C^{r}(3,7) + C^{r}(3,5) = 330 )\r\nC) ( p = C(3,7) cdot C(3,5) = 350 )\r\nD) ( p = C^{r}(7,3) cdot C^{r}(5,3) = 756 )\r\nE) ( p = C^{r}(7,3) + C^{r}(5,3) = 57 )', 'MC: We can distribute ( 7 ) identical chocolates and ( 5 ) identical packs of candy to three children in ( p ) ways, where ( p ) equals.---\r\nA) ( p = C^{r}(3,7) cdot C^{r}(3,5) = 2940 )\r\nB) ( p = C^{r}(3,7) + C^{r}(3,5) = 330 )\r\nC) ( p = C(3,7) cdot C(3,5) = 350 )\r\nD) ( p = C^{r}(7,3) cdot C^{r}(5,3) = 756 )\r\nE) ( p = C^{r}(7,3) + C^{r}(5,3) = 57 )', 'A'),
(74, 'Kombinatorika', 'Combinatorics', 'MC: Existujú štyri krvné skupiny A, B, AB, 0. Ak rozdelíme ( 10 ) osôb podľa uvedených krvných skupín, počet možných rozdelení sa rovná.---\r\nA) 286\r\nB) ( 10^4 )\r\nC) 240\r\nD) 5040\r\nE) 210', 'MC: There are four blood types A, B, AB, and 0. If we divide ( 10 ) people according to the given blood types, the number of possible distributions is.---\r\nA) 286\r\nB) ( 10^4 )\r\nC) 240\r\nD) 5040\r\nE) 210', 'B'),
(75, 'Kombinatorika', 'Combinatorics', 'MC: Na poličke v kníhkupectve je päť rovnakých slovenských kníh, tri rovnaké nemecké knihy a dve rovnaké anglické knihy. Počet spôsobov, ktorými možno knihy na poličke zoradiť sa rovná.---\r\nA) 417\r\nB) 3105\r\nC) žiadna z uvedených možností\r\nD) 2520\r\nE) 1440', 'MC: On a shelf in a bookstore, there are five identical Slovak books, three identical German books, and two identical English books. The number of ways to arrange the books on the shelf is equal to.---\r\nA) 417\r\nB) 3105\r\nC) none of the above\r\nD) 2520\r\nE) 1440', 'B'),
(76, 'Geometria', 'Geometry', 'MC: Na kruhovom ciferníku hodín zviera priamka spájajúca cifry ( 1 ) a ( 6 ) s priamkou spájajúcou cifry ( 2 ) a ( 9 ) uhol.---\r\nA) ( 30^circ )\r\nB) ( 90^circ )\r\nC) ( 60^circ )\r\nD) ( 75^circ )\r\nE) ( 45^circ )', 'MC: On a circular clock face, the angle between the line connecting the digits ( 1 ) and ( 6 ), and the line connecting the digits ( 2 ) and ( 9 ), is.---\r\nA) ( 30^circ )\r\nB) ( 90^circ )\r\nC) ( 60^circ )\r\nD) ( 75^circ )\r\nE) ( 45^circ )', 'E'),
(77, 'Trigonometria', 'Trigonometry', 'MC: Z vrcholu budovy, ktorá má výšku ( sqrt{3} cdot 10 ) metrov a od cesty je vzdialená ( 10 ) metrov, a od cesty je vzdialená ( 10 ) metrov, vidí šírku cesty pod uhlom ( 15^circ ). Cesta má šírku:---\r\nA) ( 10 (sqrt{3} - 1) ) metrov\r\nB) ( 75 ) metrov\r\nC) ( 10 (sqrt{3} + 1) ) metrov\r\nD) ( frac{sqrt{3}}{2} cdot 10 ) metrov\r\nE) ( 10 (3 - sqrt{3}) ) metrov', 'MC: From the top of a building with height ( sqrt{3} cdot 10 ) meters and distance from the road ( 10 ) meters, the width of the road is seen under an angle of ( 15^circ ). The width of the road is:---\r\nA) ( 10 (sqrt{3} - 1) ) meters\r\nB) ( 75 ) meters\r\nC) ( 10 (sqrt{3} + 1) ) meters\r\nD) ( frac{sqrt{3}}{2} cdot 10 ) meters\r\nE) ( 10 (3 - sqrt{3}) ) meters', 'C'),
(78, 'Geometria', 'Geometry', 'MC: Trojuholník má plošný obsah ( P = 3 + sqrt{3} ) a jeho uhly sú ( alpha = 45^circ, eta = 60^circ ). Dĺžky strán trojuholníka sa rovnajú.---\r\nA) ( 2, 3, 6 )\r\nB) ( sqrt{2}, sqrt{3}, sqrt{3} + sqrt{2} )\r\nC) ( 2, 3, 5 )\r\nD) ( 2, 3, 4 )\r\nE) ( 2sqrt{2}, 2sqrt{3}, sqrt{6} + sqrt{2} )', 'MC: A triangle has an area ( P = 3 + sqrt{3} ) and its angles are ( alpha = 45^circ, eta = 60^circ ). The lengths of the sides of the triangle are.---\r\nA) ( 2, 3, 6 )\r\nB) ( sqrt{2}, sqrt{3}, sqrt{3} + sqrt{2} )\r\nC) ( 2, 3, 5 )\r\nD) ( 2, 3, 4 )\r\nE) ( 2sqrt{2}, 2sqrt{3}, sqrt{6} + sqrt{2} )', 'E'),
(79, 'Geometria', 'Geometry', 'MC: V pravouhlom trojuholníku ( ABC ) sú dané odvesny ( a = 15, b = 20 ). Polomer opísanej kružnice ( r ) a vpísanej kružnice ( \rho ) sa rovnajú:---\r\nA) ( r = 15,  \rho = 7 )\r\nB) ( r = 20,  \rho = 5 )\r\nC) ( r = frac{35}{2},  \rho = 6 )\r\nD) ( r = frac{25}{2},  \rho = 5 )\r\nE) ( r = 16,  \rho = 8 )', 'MC: In a right triangle ( ABC ), the legs are ( a = 15, b = 20 ). The radius of the circumscribed circle ( r ) and the inscribed circle ( \rho ) are equal to:---\r\nA) ( r = 15,  \rho = 7 )\r\nB) ( r = 20,  \rho = 5 )\r\nC) ( r = frac{35}{2},  \rho = 6 )\r\nD) ( r = frac{25}{2},  \rho = 5 )\r\nE) ( r = 16,  \rho = 8 )', 'C'),
(80, 'Geometria', 'Geometry', 'MC: Trojuholník ( ABC ) so stranou ( c = 6 ) a pomerom uhlov ( alpha : eta : gamma = 1 : 1 : 4 ) má plošný obsah:---\r\nA) ( 2sqrt{5} )\r\nB) ( 3sqrt{2} )\r\nC) ( 3sqrt{5} )\r\nD) ( 5sqrt{5} )\r\nE) ( 2sqrt{2} )', 'MC: A triangle ( ABC ) with side ( c = 6 ) and angle ratio ( alpha : eta : gamma = 1 : 1 : 4 ) has an area equal to:---\r\nA) ( 2sqrt{5} )\r\nB) ( 3sqrt{2} )\r\nC) ( 3sqrt{5} )\r\nD) ( 5sqrt{5} )\r\nE) ( 2sqrt{2} )', 'A'),
(81, 'Geometria', 'Geometry', 'MC: Nech ( A = (2,1),  B = (5,5),  C = (3,-4) ) sú stredy protiľahlých strán trojuholníka ( ABC ). Potom vrcholy ( A, B, C ) majú súradnice:---\r\nA) ( A = (6,2),  B = (0,6),  C = (4,8) )\r\nB) ( A = (-6,2),  B = (0,6),  C = (4,8) )\r\nC) ( A = (6,-2),  B = (0,-6),  C = (4,8) )\r\nD) ( A = (-6,2),  B = (0,-6),  C = (-4,8) )\r\nE) ( A = (-6,-2),  B = (0,6),  C = (-4,-8) )', 'MC: Let ( A = (2,1),  B = (5,5),  C = (3,-4) ) be the midpoints of the sides of triangle ( ABC ). Then the coordinates of the vertices ( A, B, C ) are:---\r\nA) ( A = (6,2),  B = (0,6),  C = (4,8) )\r\nB) ( A = (-6,2),  B = (0,6),  C = (4,8) )\r\nC) ( A = (6,-2),  B = (0,-6),  C = (4,8) )\r\nD) ( A = (-6,2),  B = (0,-6),  C = (-4,8) )\r\nE) ( A = (-6,-2),  B = (0,6),  C = (-4,-8) )', 'A'),
(82, 'Geometria', 'Geometry', 'MC: Rovnica kružnice prechádzajúcej bodmi ( A = (1,1),  B = (1,-1),  C = (2,0) ) je:---\r\nA) ( x^2 + y^2 = 1 )\r\nB) ( (x - 1)^2 - y^2 = 1 )\r\nC) ( (x - 1)^2 + y^2 = 1 )\r\nD) ( (x - 1)^2 + (y + 1)^2 = 1 )\r\nE) ( x^2 + (y - 1)^2 = 1 )', 'MC: The equation of the circle passing through the points ( A = (1,1),  B = (1,-1),  C = (2,0) ) is:---\r\nA) ( x^2 + y^2 = 1 )\r\nB) ( (x - 1)^2 - y^2 = 1 )\r\nC) ( (x - 1)^2 + y^2 = 1 )\r\nD) ( (x - 1)^2 + (y + 1)^2 = 1 )\r\nE) ( x^2 + (y - 1)^2 = 1 )', 'C'),
(83, 'Geometria', 'Geometry', 'MC: Rovnina hyperboly so stredom v začiatku, s ohniskami na osi ( x ), na ktorej leží bod ( M = left(-1, frac{9}{2} \right) ) a ktorej asymptoty majú rovnice ( y = pm frac{3}{2}x ), je:---\r\nA) ( frac{x^2}{18} - frac{y^2}{8} = 1 )\r\nB) ( frac{x^2}{8} - frac{y^2}{18} = 1 )\r\nC) C: taká hyperbola neexistuje\r\nD) ( frac{y^2}{18} - frac{x^2}{8} = 1 )\r\nE) ( frac{y^2}{25} - frac{x^2}{9} = 1 )', 'MC: The equation of a hyperbola centered at the origin, with foci on the ( x )-axis, passing through the point ( M = left(-1, frac{9}{2} \right) ), and having asymptotes ( y = pm frac{3}{2}x ), is:---\r\nA) ( frac{x^2}{18} - frac{y^2}{8} = 1 )\r\nB) ( frac{x^2}{8} - frac{y^2}{18} = 1 )\r\nC) such hyperbola does not exist\r\nD) ( frac{y^2}{18} - frac{x^2}{8} = 1 )\r\nE) ( frac{y^2}{25} - frac{x^2}{9} = 1 )', 'A'),
(84, 'Geometria', 'Geometry', 'MC: Parabola prechádzajúca bodom ( A = (-5,4) ), má dotyčnicu s rovnicou ( y - 3 = 0 ) vo svojom vrchole. Jej os má rovnicu ( x + 7 = 0 ). Rovnica paraboly je:---\r\nA) ( (x + 7)^2 = 4(y - 5) )\r\nB) ( (x + 7)^2 = 4(y - 3) )\r\nC) ( (x - 7)^2 = 4(y + 3) )\r\nD) ( (x + 3)^2 = 4(y - 7) )\r\nE) ( (x - 3)^2 = 4(y + 7) )', 'MC: A parabola passing through point ( A = (-5,4) ), has a tangent line ( y - 3 = 0 ) at its vertex. Its axis has the equation ( x + 7 = 0 ). The equation of the parabola is:---\r\nA) ( (x + 7)^2 = 4(y - 5) )\r\nB) ( (x + 7)^2 = 4(y - 3) )\r\nC) ( (x - 7)^2 = 4(y + 3) )\r\nD) ( (x + 3)^2 = 4(y - 7) )\r\nE) ( (x - 3)^2 = 4(y + 7) )', 'A'),
(85, 'Geometria', 'Geometry', 'MC: Bod ( M = (3, -1) ) je koncový bod vedľajšej osi elipsy. Ohniská elipsy ležia na priamke ( p: y + 6 = 0 ). Pre jej excentricitu a dĺžku hlavnej poloosi platí ( frac{c}{a} = frac{sqrt{2}}{2} ). Elipsa má rovnicu:---\r\nA) ( frac{(x + 3)^2}{50} + frac{(y - 6)^2}{25} = 1 )\r\nB) ( frac{(x + 3)^2}{50} + frac{(y + 6)^2}{25} = 1 )\r\nC) ( frac{(x - 3)^2}{50} + frac{(y + 6)^2}{25} = 1 )\r\nD) ( frac{(x - 3)^2}{25} + frac{(y + 6)^2}{16} = 1 )\r\nE) ( frac{(x - 8)^2}{36} + frac{(y + 1)^2}{25} = 1 )', 'MC: The point ( M = (3, -1) ) is the endpoint of the minor axis of an ellipse. The foci of the ellipse lie on the line ( p: y + 6 = 0 ). For its eccentricity and the length of the semi-major axis it holds that ( frac{c}{a} = frac{sqrt{2}}{2} ). The equation of the ellipse is:---\r\nA) ( frac{(x + 3)^2}{50} + frac{(y - 6)^2}{25} = 1 )\r\nB) ( frac{(x + 3)^2}{50} + frac{(y + 6)^2}{25} = 1 )\r\nC) ( frac{(x - 3)^2}{50} + frac{(y + 6)^2}{25} = 1 )\r\nD) ( frac{(x - 3)^2}{25} + frac{(y + 6)^2}{16} = 1 )\r\nE) ( frac{(x - 8)^2}{36} + frac{(y + 1)^2}{25} = 1 )', 'C'),
(86, 'Stereometria', 'Solid Geometry', 'MC: Objem zrezaného kužeľa, ktorého podstavy sú kruhy opísané a vpísané dvom rovnostranným stenám kocky s dĺžkou hrany ( a ), sa rovná:---\r\nA) ( V = frac{1}{12} pi sqrt{3} a^2 )\r\nB) ( V = frac{1}{4} pi sqrt{3} a^2 )\r\nC) ( V = frac{1}{12} pi a^2 (3 + sqrt{2}) )\r\nD) ( V = frac{1}{4} pi a^2 )\r\nE) ( V = frac{1}{12} pi a^2 )', 'MC: The volume of a truncated cone whose bases are circles inscribed and circumscribed to two equilateral faces of a cube with edge length ( a ) is:---\r\nA) ( V = frac{1}{12} pi sqrt{3} a^2 )\r\nB) ( V = frac{1}{4} pi sqrt{3} a^2 )\r\nC) ( V = frac{1}{12} pi a^2 (3 + sqrt{2}) )\r\nD) ( V = frac{1}{4} pi a^2 )\r\nE) ( V = frac{1}{12} pi a^2 )', 'A'),
(87, 'Geometria', 'Geometry', 'MC: Rovnica roviny ( alpha ), ktorá obsahuje bod ( A = [2, -1, -4] ) a je kolmá na priamku ( p : [x,y,z] = [3 - 2t, 4t, 7] ), je:---\r\nA) ( alpha: 2x - 3y - 15 = 0 )\r\nB) ( alpha: x - 2y - 5 = 0 )\r\nC) ( alpha: -2x + y + 4 = 0 )\r\nD) ( alpha: -2 + 2y + 5 = 0 )\r\nE) ( alpha: 2x - y - 5 = 0 )', 'MC: The equation of the plane ( alpha ) that contains the point ( A = [2, -1, -4] ) and is perpendicular to the line ( p : [x,y,z] = [3 - 2t, 4t, 7] ) is:---\r\nA) ( alpha: 2x - 3y - 15 = 0 )\r\nB) ( alpha: x - 2y - 5 = 0 )\r\nC) ( alpha: -2x + y + 4 = 0 )\r\nD) ( alpha: -2 + 2y + 5 = 0 )\r\nE) ( alpha: 2x - y - 5 = 0 )', 'C');
INSERT INTO `questions` (`id`, `area`, `area_en`, `text_sk`, `text_en`, `correct_answer`) VALUES
(88, 'Geometria', 'Geometry', 'MC: Rovnica priamky ( p ), ktorá prechádza bodom ( P = [-5,1,0] ), je kolmá na priamku ( q: [x,y,z] = [3t, 1 - 2t, -4 + t] ), s ktorou je rýchlosť robenia sa rovná:---\r\nA) ( p: [x,y,z] = [-5 + 7t, 1 + 2t, -6t] )\r\nB) ( p: [x,y,z] = [-5 + 3t, 1 + t, 7t] )\r\nC) ( p: [x,y,z] = [-5 + t, 1 + 2t, 6t] )\r\nD) ( p: [x,y,z] = [-5 + 3t, 1 + 22t, -67t] )\r\nE) ( p: [x,y,z] = [-5 + 27t, 1 + 22t, -67t] )', 'MC: The equation of the line ( p ), passing through the point ( P = [-5,1,0] ), perpendicular to the line ( q: [x,y,z] = [3t, 1 - 2t, -4 + t] ), is:---\r\nA) ( p: [x,y,z] = [-5 + 7t, 1 + 2t, -6t] )\r\nB) ( p: [x,y,z] = [-5 + 3t, 1 + t, 7t] )\r\nC) ( p: [x,y,z] = [-5 + t, 1 + 2t, 6t] )\r\nD) ( p: [x,y,z] = [-5 + 3t, 1 + 22t, -67t] )\r\nE) ( p: [x,y,z] = [-5 + 27t, 1 + 22t, -67t] )', 'A'),
(89, 'Geometria', 'Geometry', 'MC: Guľová plocha s polomerom ( 4 ), ktorej stred leží na priamke ( x = [-2 + 3t, 8 + 4t, 6 - 5t],  t in mathbb{R} ), sa dotýka roviny ( y = 0 ). Jej rovnica je:---\r\nA) ( (x + 1)^2 + (y - 4)^2 + (z + 9)^2 = 16,  (x + 5)^2 + (y - 4)^2 + (z - 1)^2 = 16 )\r\nB) ( (x + 1)^2 + (y + 4)^2 + (z + 9)^2 = 25,  (x + 5)^2 + (y - 4)^2 + (z - 1)^2 = 25 )\r\nC) ( (x + 10)^2 + (y + 5)^2 + (z + 10)^2 = 16,  (x + 5)^2 + (y - 4)^2 + (z - 1)^2 = 16 )\r\nD) ( (x + 1)^2 + (y + 4)^2 + (z - 2)^2 = 16,  (x + 5)^2 + (y - 4)^2 + (z - 1)^2 = 16 )\r\nE) ( (x + 1)^2 + (y + 4)^2 + (z + 9)^2 = 16,  (x + 5)^2 + (y - 4)^2 + (z - 1)^2 = 16 )', 'MC: A sphere with radius ( 4 ), whose center lies on the line ( x = [-2 + 3t, 8 + 4t, 6 - 5t],  t in mathbb{R} ), is tangent to the plane ( y = 0 ). Its equation is:---\r\nA) ( (x + 1)^2 + (y - 4)^2 + (z + 9)^2 = 16,  (x + 5)^2 + (y - 4)^2 + (z - 1)^2 = 16 )\r\nB) ( (x + 1)^2 + (y + 4)^2 + (z + 9)^2 = 25,  (x + 5)^2 + (y - 4)^2 + (z - 1)^2 = 25 )\r\nC) ( (x + 10)^2 + (y + 5)^2 + (z + 10)^2 = 16,  (x + 5)^2 + (y - 4)^2 + (z - 1)^2 = 16 )\r\nD) ( (x + 1)^2 + (y + 4)^2 + (z - 2)^2 = 16,  (x + 5)^2 + (y - 4)^2 + (z - 1)^2 = 16 )\r\nE) ( (x + 1)^2 + (y + 4)^2 + (z + 9)^2 = 16,  (x + 5)^2 + (y - 4)^2 + (z - 1)^2 = 16 )', 'E'),
(90, 'Geometria', 'Geometry', 'MC: Rovnica dotykovej roviny ku guľovej ploche ( (x + 1)^2 + (y - 4)^2 + (z - 2)^2 = 25 ), ktorá je rovnobežná s rovinou ( alpha: x - 8y - 4z + 7 = 0 ), sa rovná:---\r\nA) ( x - 8y - 4z - 4 = 0,  x - 8y - 4z + 86 = 0 )\r\nB) ( x - 8y - 4z - 5 = 0,  x - 8y - 4z + 25 = 0 )\r\nC) ( x - 8y - 4z - 10 = 0,  x - 8y - 4z + 10 = 0 )\r\nD) ( x - 8y - 4z - 6 = 0,  x - 8y - 4z + 6 = 0 )\r\nE) ( x - 8y - 4z + 4 = 0,  x - 8y - 4z - 86 = 0 )', 'MC: The equation of the tangent plane to the sphere ( (x + 1)^2 + (y - 4)^2 + (z - 2)^2 = 25 ), which is parallel to the plane ( alpha: x - 8y - 4z + 7 = 0 ), is:---\r\nA) ( x - 8y - 4z - 4 = 0,  x - 8y - 4z + 86 = 0 )\r\nB) ( x - 8y - 4z - 5 = 0,  x - 8y - 4z + 25 = 0 )\r\nC) ( x - 8y - 4z - 10 = 0,  x - 8y - 4z + 10 = 0 )\r\nD) ( x - 8y - 4z - 6 = 0,  x - 8y - 4z + 6 = 0 )\r\nE) ( x - 8y - 4z + 4 = 0,  x - 8y - 4z - 86 = 0 )', 'C'),
(91, 'Algebra', 'Algebra', 'MC: Výraz ( sqrt{x^2 - 2 + frac{1}{x^2}} ) sa pre ( x \ne 0 ) rovná výrazu:---\r\nA) ( x - 1 )\r\nB) žiadna z uvedených možností\r\nC) ( left| x - frac{1}{x} \right| )\r\nD) ( x - frac{1}{x} )\r\nE) ( frac{1}{x} - x )', 'MC: The expression ( sqrt{x^2 - 2 + frac{1}{x^2}} ) for ( x \ne 0 ) is equal to:---\r\nA) ( x - 1 )\r\nB) none of the above\r\nC) ( left| x - frac{1}{x} \right| )\r\nD) ( x - frac{1}{x} )\r\nE) ( frac{1}{x} - x )', 'C'),
(92, 'Algebra', 'Algebra', 'MC: Úpravou výrazu ( left( frac{1}{a+1} - frac{2a}{a^2 - 1} \right) left( frac{1}{a - 1} \right) ) dostaneme:---\r\nA) ( frac{1}{a^2 - 1} ) pre ( a \ne -1,  a \ne 1 )\r\nB) ( frac{1}{1 - a} ) pre ( a \ne 1 )\r\nC) ( frac{1}{a - 1} ) pre ( a \ne 0,  a \ne 1 )\r\nD) ( frac{1}{a} ) pre ( a \ne 0,  a \ne -1,  a \ne 1 )\r\nE) ( frac{1}{1 - a^2} ) pre ( a \ne -1,  a \ne 1 )', 'MC: Simplifying the expression ( left( frac{1}{a+1} - frac{2a}{a^2 - 1} \right) left( frac{1}{a - 1} \right) ) gives:---\r\nA) ( frac{1}{a^2 - 1} ) for ( a \ne -1,  a \ne 1 )\r\nB) ( frac{1}{1 - a} ) for ( a \ne 1 )\r\nC) ( frac{1}{a - 1} ) for ( a \ne 0,  a \ne 1 )\r\nD) ( frac{1}{a} ) for ( a \ne 0,  a \ne -1,  a \ne 1 )\r\nE) ( frac{1}{1 - a^2} ) for ( a \ne -1,  a \ne 1 )', 'E'),
(93, 'Algebra', 'Algebra', 'MC: Kvadratický trojčlen ( 3x^2 - 4x + 4 ) sa dá rozložiť v ( mathbb{R} ) na súčin lineárnych výrazov:---\r\nA) nedá sa rozložiť\r\nB) ( 3(x + frac{1}{6})(x - frac{2}{3}) )\r\nC) ( 3(x - frac{1}{3})(x - frac{4}{3}) )\r\nD) nedá sa – neplatí žiadna možnosť\r\nE) ( (x - frac{1}{3})(x + frac{1}{6}) )', 'MC: The quadratic trinomial ( 3x^2 - 4x + 4 ) can be factored in ( mathbb{R} ) into a product of linear terms:---\r\nA) cannot be factored\r\nB) ( 3(x + frac{1}{6})(x - frac{2}{3}) )\r\nC) ( 3(x - frac{1}{3})(x - frac{4}{3}) )\r\nD) none of the options apply\r\nE) ( (x - frac{1}{3})(x + frac{1}{6}) )', 'A'),
(94, 'Algebra', 'Algebra', 'MC: Riešením rovnice ( 2|x + 2| = |x| + 6 ) v ( mathbb{R} ) je:---\r\nA) ( K = {2, 10} )\r\nB) ( K = {4, 11} )\r\nC) ( K = {3, 10} )\r\nD) ( K = {-10, 2} )\r\nE) ( K = emptyset )', 'MC: The solution of the equation ( 2|x + 2| = |x| + 6 ) in ( mathbb{R} ) is:---\r\nA) ( K = {2, 10} )\r\nB) ( K = {4, 11} )\r\nC) ( K = {3, 10} )\r\nD) ( K = {-10, 2} )\r\nE) ( K = emptyset )', 'A'),
(95, 'Algebra', 'Algebra', 'MC: Určte všetky hodnoty parametra ( p ), pre ktoré rovnica ( px^2 = x + p ) nemá v ( mathbb{R} ) riešenie:---\r\nA) ( p geq 4 )\r\nB) ( p = -1  lor  p = 1 )\r\nC) ( p = 1 )\r\nD) ( p = -1 )\r\nE) ( p = 3 )', 'MC: Determine all values of the parameter ( p ) for which the equation ( px^2 = x + p ) has no solution in ( mathbb{R} ):---\r\nA) ( p geq 4 )\r\nB) ( p = -1  lor  p = 1 )\r\nC) ( p = 1 )\r\nD) ( p = -1 )\r\nE) ( p = 3 )', 'B'),
(96, 'Algebra', 'Algebra', 'MC: Sústava rovníc ( x + y = 4, quad x^2 + y^2 = 10 ) má riešenie:---\r\nA) ( K = {(1,3), (3,1)} )\r\nB) ( K = {(3,1)} )\r\nC) nemá riešenie\r\nD) ( K = {(1,3)} )\r\nE) ( K = {(1,2), (2,1)} )', 'MC: The system of equations ( x + y = 4, quad x^2 + y^2 = 10 ) has the solution:---\r\nA) ( K = {(1,3), (3,1)} )\r\nB) ( K = {(3,1)} )\r\nC) no solution\r\nD) ( K = {(1,3)} )\r\nE) ( K = {(1,2), (2,1)} )', 'A'),
(97, 'Algebra', 'Algebra', 'MC: Riešením nerovnice ( |2x + 3| geq 9 ) v ( mathbb{R} ) je:---\r\nA) ( P = (-5, 3) )\r\nB) ( P = (-infty, -6) cup (3, infty) )\r\nC) ( P = (2, 8) )\r\nD) ( P = (-6, 3) )\r\nE) ( P = (-infty, -6] cup [3, infty) )', 'MC: The solution of the inequality ( |2x + 3| geq 9 ) in ( mathbb{R} ) is:---\r\nA) ( P = (-5, 3) )\r\nB) ( P = (-infty, -6) cup (3, infty) )\r\nC) ( P = (2, 8) )\r\nD) ( P = (-6, 3) )\r\nE) ( P = (-infty, -6] cup [3, infty) )', 'E'),
(98, 'Funkcie', 'Functions', 'MC: Grafy funkcií ( f(x) = 3^x ) a ( g(x) = left( frac{1}{3} \right)^x ) sa pretínajú v bode:---\r\nA) a) nepretínajú sa\r\nB) ( [1, 0] )\r\nC) ( [2, 4] )\r\nD) ( [0, 1] )\r\nE) ( [0, frac{1}{2}] )', 'MC: The graphs of functions ( f(x) = 3^x ) and ( g(x) = left( frac{1}{3} \right)^x ) intersect at the point:---\r\nA) They do not intersect\r\nB) ( [1, 0] )\r\nC) ( [2, 4] )\r\nD) ( [0, 1] )\r\nE) ( [0, frac{1}{2}] )', 'D'),
(99, 'Logaritmy', 'Logarithms', 'MC: ( log_3 left( frac{1}{9} \right) = ):---\r\nA) 2\r\nB) -2\r\nC) nie je definovaný\r\nD) -3\r\nE) -4', 'MC: ( log_3 left( frac{1}{9} \right) = ):---\r\nA) 2\r\nB) -2\r\nC) not defined\r\nD) -3\r\nE) -4', 'B'),
(100, 'Goniometria', 'Trigonometry', 'MC: Riešením rovnice ( 2 cos x = -2 ) v intervale ( (0, 2pi) ) je:---\r\nA) ( K = left{ frac{5pi}{6}, frac{7pi}{6} \right} )\r\nB) ( K = left{ frac{pi}{2}, frac{3pi}{2} \right} )\r\nC) ( K = emptyset )\r\nD) ( K = left{ frac{3pi}{4}, frac{7pi}{4} \right} )\r\nE) ( K = left{ frac{2pi}{3}, pi, frac{4pi}{3} \right} )', 'MC: The solution of the equation ( 2 cos x = -2 ) in the interval ( (0, 2pi) ) is:---\r\nA) ( K = left{ frac{5pi}{6}, frac{7pi}{6} \right} )\r\nB) ( K = left{ frac{pi}{2}, frac{3pi}{2} \right} )\r\nC) ( K = emptyset )\r\nD) ( K = left{ frac{3pi}{4}, frac{7pi}{4} \right} )\r\nE) ( K = left{ frac{2pi}{3}, pi, frac{4pi}{3} \right} )', 'C'),
(101, 'Logaritmy', 'Logarithms', 'MC: Funkcia ( y = log_a x ) je:---\r\nA) klesajúca ( forall x in mathbb{R} )\r\nB) inverzná k funkcii ( y = a^x )\r\nC) definovaná ( forall x in mathbb{R} )\r\nD) rastúca pre ( a > 0 ), klesajúca pre ( a < 0 )\r\nE) definovaná pre ( x > 0,  a > 0,  a \ne 1 )', 'MC: The function ( y = log_a x ) is:---\r\nA) decreasing ( forall x in mathbb{R} )\r\nB) inverse to the function ( y = a^x )\r\nC) defined ( forall x in mathbb{R} )\r\nD) increasing for ( a > 0 ), decreasing for ( a < 0 )\r\nE) defined for ( x > 0,  a > 0,  a \ne 1 )', 'E'),
(102, 'Aritmetika', 'Arithmetic', 'MC: Súčtom čísel ( 2 + 4 + 6 + 8 + dots + 198 + 200 ) je:---\r\nA) 19876\r\nB) 10010\r\nC) milión\r\nD) 10100\r\nE) 12675', 'MC: The sum of the numbers ( 2 + 4 + 6 + 8 + dots + 198 + 200 ) is:---\r\nA) 19876\r\nB) 10010\r\nC) million\r\nD) 10100\r\nE) 12675', 'B'),
(103, 'Postupnosti', 'Sequences', 'MC: Aké číslo ( x ) treba pripočítať k číslam ( 2, 7, 17 ), aby tvorili tri za sebou idúce členy geometrickej postupnosti:---\r\nA) ( x = 1 )\r\nB) ( x = 3 )\r\nC) ( x = 0 )\r\nD) ( x = -3 )\r\nE) ( x = 2 )', 'MC: What number ( x ) must be added to the numbers ( 2, 7, 17 ) so that they form three consecutive terms of a geometric sequence:---\r\nA) ( x = 1 )\r\nB) ( x = 3 )\r\nC) ( x = 0 )\r\nD) ( x = -3 )\r\nE) ( x = 2 )', 'A'),
(104, 'Geometria', 'Geometry', 'MC: Pytagorova veta znie:---\r\nA) ( a^2 = c - c_a )\r\nB) obsah štvorca je rovný druhej mocnine dĺžky jeho strany\r\nC) obsah štvorca nad preponou pravouhlého trojuholníka je rovný súčtu obsahov štvorcov nad oboma odvesnami\r\nD) ( b^2 = c - c_a )\r\nE) všetky uhly nad priemerom sú pravé', 'MC: The Pythagorean theorem says:---\r\nA) ( a^2 = c - c_a )\r\nB) the area of a square is equal to the square of the length of its side\r\nC) the area of the square over the hypotenuse of a right triangle is equal to the sum of the areas of the squares over the two legs\r\nD) ( b^2 = c - c_a )\r\nE) all angles above a semicircle are right angles', 'C'),
(105, 'Geometria', 'Geometry', 'MC: V kružnici s polomerom ( r = 7 ) je vzdialenosť tetivy ( AB ) od stredu kružnice ( d = 3 ). Dĺžka tetivy je:---\r\nA) 4\r\nB) ( 4sqrt{10} )\r\nC) ( 3sqrt{2} )\r\nD) 6\r\nE) ( 2sqrt{5} )', 'MC: In a circle with radius ( r = 7 ), the distance of a chord ( AB ) from the center is ( d = 3 ). The length of the chord is:---\r\nA) 4\r\nB) ( 4sqrt{10} )\r\nC) ( 3sqrt{2} )\r\nD) 6\r\nE) ( 2sqrt{5} )', 'B'),
(106, 'Geometria', 'Geometry', 'MC: Hyperbola ( frac{(x - 1)^2}{16} - frac{(y + 2)^2}{9} = 1 ) má excentricitu:---\r\nA) ( e = 2sqrt{3} )\r\nB) ( e = sqrt{5} )\r\nC) ( e = sqrt{8} )\r\nD) ( e = 5 )\r\nE) hyperbola nemá excentricitu', 'MC: The hyperbola ( frac{(x - 1)^2}{16} - frac{(y + 2)^2}{9} = 1 ) has eccentricity:---\r\nA) ( e = 2sqrt{3} )\r\nB) ( e = sqrt{5} )\r\nC) ( e = sqrt{8} )\r\nD) ( e = 5 )\r\nE) the hyperbola has no eccentricity', 'A'),
(107, 'Geometria', 'Geometry', 'MC: Rovnica ( x^2 - 4x + 6y - 2 = 0 ) je:---\r\nA) rovnica kružnice so stredom v bode ( S = [2, 1] )\r\nB) rovnica paraboly s vrcholom v bode ( V = [2, 1] ), ktorá je rovnobežná s osou ( o_x )\r\nC) rovnica hyperboly so stredom v bode ( S = [2, 1] )\r\nD) rovnica paraboly s vrcholom v bode ( V = [2, 1] ), ktorá je rovnobežná s osou ( o_y )\r\nE) rovnica elipsy so stredom v bode ( S = [2, 1] )', 'MC: The equation ( x^2 - 4x + 6y - 2 = 0 ) is:---\r\nA) equation of a circle centered at ( S = [2, 1] )\r\nB) equation of a parabola with vertex at ( V = [2, 1] ), parallel to the ( x )-axis\r\nC) equation of a hyperbola centered at ( S = [2, 1] )\r\nD) equation of a parabola with vertex at ( V = [2, 1] ), parallel to the ( y )-axis\r\nE) equation of an ellipse centered at ( S = [2, 1] )', 'B'),
(108, 'Geometria', 'Geometry', 'MC: Vzdialenosť stredu vpísanej kružnice od vrchola ( S subset 	riangle ABC ) pravouhlého trojuholníka s uhlom ( angle ACB = 90^circ ) je ( sqrt{8} ). Polomer kružnice vpísanej do trojuholníka ( ABC ) je:---\r\nA) 1\r\nB) ( 2sqrt{3} )\r\nC) 2\r\nD) ( frac{3sqrt{2}}{2} )\r\nE) ( sqrt{2} )', 'MC: The distance of the incenter from vertex ( C ) of a right triangle ( ABC ) with ( angle ACB = 90^circ ) is ( sqrt{8} ). The inradius of triangle ( ABC ) is:---\r\nA) 1\r\nB) ( 2sqrt{3} )\r\nC) 2\r\nD) ( frac{3sqrt{2}}{2} )\r\nE) ( sqrt{2} )', 'E'),
(109, 'Funkcie', 'Functions', 'MC: Obor hodnôt funkcie ( y = 2 + 5 sin 3x ) je:---\r\nA) ( (-3, 10) )\r\nB) ( (-3, 7) )\r\nC) ( (-4, 8) )\r\nD) ( (-3, 7\rangle )\r\nE) ( langle -1, 7\rangle )', 'MC: The range of the function ( y = 2 + 5 sin 3x ) is:---\r\nA) ( (-3, 10) )\r\nB) ( (-3, 7) )\r\nC) ( (-4, 8) )\r\nD) ( (-3, 7\rangle )\r\nE) ( langle -1, 7\rangle )', 'B'),
(110, 'Geometria', 'Geometry', 'MC: Pre ktoré hodnoty ( k ) sa priamka ( p: y = kx + 2 ) dotýka paraboly ( y = x^2 + 3x + 3 ):---\r\nA) ( k in {0, 6} )\r\nB) ( k in {1, 5} )\r\nC) ( k in (-infty, 1) cup (5, infty) )\r\nD) ( k in (1, 5) )\r\nE) ( k in (-infty, 5) cup (10, infty) )', 'MC: For which values of ( k ) does the line ( p: y = kx + 2 ) touch the parabola ( y = x^2 + 3x + 3 ):---\r\nA) ( k in {0, 6} )\r\nB) ( k in {1, 5} )\r\nC) ( k in (-infty, 1) cup (5, infty) )\r\nD) ( k in (1, 5) )\r\nE) ( k in (-infty, 5) cup (10, infty) )', 'B');

-- --------------------------------------------------------

--
-- Table structure for table `tests`
--

CREATE TABLE `tests` (
  `id` int NOT NULL,
  `user_id` int NOT NULL,
  `datetime` datetime NOT NULL,
  `city` varchar(100) COLLATE utf8mb4_slovak_ci DEFAULT NULL,
  `country` varchar(100) COLLATE utf8mb4_slovak_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_slovak_ci;

--
-- Dumping data for table `tests`
--

INSERT INTO `tests` (`id`, `user_id`, `datetime`, `city`, `country`) VALUES
(4, 2, '2025-05-18 00:51:14', 'Bratislava', 'Slovensko');

-- --------------------------------------------------------

--
-- Table structure for table `test_questions`
--

CREATE TABLE `test_questions` (
  `id` int NOT NULL,
  `test_id` int NOT NULL,
  `question_id` int NOT NULL,
  `answered_correctly` tinyint(1) DEFAULT NULL,
  `time_taken` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_slovak_ci;

--
-- Dumping data for table `test_questions`
--

INSERT INTO `test_questions` (`id`, `test_id`, `question_id`, `answered_correctly`, `time_taken`) VALUES
(5, 4, 5, 0, 5.7);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int NOT NULL,
  `username` varchar(50) COLLATE utf8mb4_slovak_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_slovak_ci NOT NULL,
  `api_token` varchar(64) COLLATE utf8mb4_slovak_ci DEFAULT NULL,
  `admin` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_slovak_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `password`, `api_token`, `admin`) VALUES
(2, 'xhusek@stuba.sk', '$2y$10$u0PayNPtcmeNrbFrxg8Bt.j6nriuOuzEXkBIRdw5ygrU0d894iMNy', '8b6f48f15f9b17af2847ae14e2df0bd95aaa41601cc4537720b7c5534905dd7a', 0),
(3, 'marekdurica229@gmail.com', '$2y$10$lsXBMB0CPnsj0JzhRnsJSuJBlg7rlWBLwEn8jT7GMatgRYZKU8LkS', '36f0d359db455beef2f659b09dad25dd8cc31fc6faa97511f9c7bef6caa797bb', NULL),
(4, 'admin', '$2y$10$8YYRaWEATEzBmyPGW5Eby.j1uvODSnAFRxitLwlG13m4HDCGRkQ4S', 'c670fecd3719dd0a12640c9f3a89de0e12562c9ba9ec3135060d05bfc41749ea', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `questions`
--
ALTER TABLE `questions`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tests`
--
ALTER TABLE `tests`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_id` (`user_id`);

--
-- Indexes for table `test_questions`
--
ALTER TABLE `test_questions`
  ADD PRIMARY KEY (`id`),
  ADD KEY `test_id` (`test_id`),
  ADD KEY `question_id` (`question_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `questions`
--
ALTER TABLE `questions`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=111;

--
-- AUTO_INCREMENT for table `tests`
--
ALTER TABLE `tests`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `test_questions`
--
ALTER TABLE `test_questions`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `tests`
--
ALTER TABLE `tests`
  ADD CONSTRAINT `tests_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);

--
-- Constraints for table `test_questions`
--
ALTER TABLE `test_questions`
  ADD CONSTRAINT `test_questions_ibfk_1` FOREIGN KEY (`test_id`) REFERENCES `tests` (`id`),
  ADD CONSTRAINT `test_questions_ibfk_2` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
